### ISSUE TITLE
Unexpected behaviour on iPad with Apple Pencil during create connection for any shape elements

### ISSUE THREAD

**Issue by nixorg** [jgraph/drawio#3256] opened 2022-12-20 09:51 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I faced with unexpected behaviour on iPad with Apple Pencil during adding any connected element for any element. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any diagram
2. Select any element (Rectangle, for example)
3. Put it on the screen
5. Select rectangle to get focus (See 4 arrows in all direction)
6. Choose any arrow and tap with Pencil on them
7. See set of shapes to connect
8. Select any with Apple Pencil (if I use finger, everything is OK)
9. See unexpected jump to somewhere of the screen

**Expected behavior**
I expect no jump once I select shape connection with Apple Pencil 

**Screenshots**
https://ibb.co/Qrcb0XN
https://ibb.co/P19hSws
https://ibb.co/J3KJSRL

**draw.io version 

- draw.io version 20.7.4

**Tablet
 - OS: iOS
 - Browser safari

**Comment by alderg** [comment] 2022-12-22 09:12
We're unable to reproduce this. What version of iOS/iPadOS and which version of the Apple pencil? For the "select" step: Is this just tap and release or tap, drag and release with the pencil?

**Comment by nixorg** [comment] 2022-12-23 11:34
iOS version is 16.2. iPad Pro 2018 11" and Apple Pencil 2. 
Here is the video record https://www.dropbox.com/s/qhl4jg90yt6dumm/IMG_3254.MOV?dl=0

**Comment by alderg** [comment] 2023-02-23 09:53
Thanks for the report. This will be fixed in the next release.

**Closed by alderg** 2023-02-23 09:53 UTC
Labels: bug

**Comment by davidjgraph** [comment] 2023-03-02 11:18
Released in 20.8.24
