### ISSUE TITLE
Not a diagram file (error on line 1 at column 1: Document is empty)

### ISSUE THREAD

**Issue by rushikeshb123** [jgraph/drawio#4013] opened 2023-11-30 09:12 UTC
Getting error in [draw.io](http://draw.io/) "Not a diagram file (error on line 1 at column 1: Document is empty)" while opening the pdf file which were exported earlier from [draw.io](http://draw.io/). At the time, I exported two distinct files, but now I can only open one of them on draw.io and the other cannot be opened.

**Comment by alderg** [comment] 2023-11-30 09:27
Please attach the PDF file.

**Comment by davidjgraph** [comment] 2023-11-30 09:38
Duplicate of https://groups.google.com/g/drawio/c/OO1BOUNISvk/m/Ca230FpgAgAJ

**Closed by davidjgraph** 2023-11-30 09:38 UTC

**Comment by rushikeshb123** [comment] 2023-11-30 10:02
Attaching PDF
[Wireframe_Vehicle Logbook Driver app_v1.1_20230313.drawio.pdf (1).pdf](https://github.com/jgraph/drawio/files/13511282/Wireframe_Vehicle.Logbook.Driver.app_v1.1_20230313.drawio.pdf.1.pdf)
![Error SS](https://github.com/jgraph/drawio/assets/152484423/2b98f4b0-c17f-49aa-bb4b-878573893325)

**Comment by davidjgraph** [comment] 2023-11-30 10:09
Please just stick the google groups post. You've posted in 3 places now.
