### ISSUE TITLE
Add Salesforce diagrams icons to library

### ISSUE THREAD

**Issue by egrimate** [jgraph/drawio#3399] opened 2023-03-03 07:21 UTC
**Is your feature request related to a problem?**
No, I would like icons to be added

**Describe the solution you'd like**
Now Salesforce have a design guide to make diagrams using design Templates.

_Originally posted by @ernestovalent in https://github.com/jgraph/drawio/discussions/3169_

**Comment by jonathanwiesel** [comment] 2023-06-05 12:12
Seems like duplicate of #2793 but that one got locked

**Comment by davidjgraph** [comment] 2023-09-27 12:01
@jonathanwiesel we don't care who adds what or what other tools do. These are off-topic.

**Comment by jonathanwiesel** [comment] 2023-09-27 13:14
@davidjgraph just wanted to share it since knowing what the competition does for the same request / requirement gives a better understanding of the audience, needs and positioning of a feature in the product which also helps in priorization.

However if you don't find it useful or consider it harmful I'll avoid sharing in that regard, was not my intention to generate conflict

**Comment by davidjgraph** [comment] 2023-09-27 13:26
Duplicate #2793

**Closed by davidjgraph** 2023-09-27 13:26 UTC
