### ISSUE TITLE
Allow Different Default Shapes on Connection Menu.

### ISSUE THREAD

**Issue by deadlyBuzz** [jgraph/drawio#4644] opened 2024-09-06 12:53 UTC
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I use Drawio to create UML Activity diagrams that describe how a system is to behave, and I find the Default shapes from an the connection menu (Hovering on the floating arrow) don't suit the style I'm looking to use
![image](https://github.com/user-attachments/assets/3077e9d7-cc18-4e83-bddf-09203052a76a)

**Describe the solution you'd like**
I'd like a Mechanism to load or adjust these pieces so I can define the shapes that are on this menu for each type of UML chart I'm developing.

**Describe alternatives you've considered**
At present, the only way is to have a custom Shape Library and drag each over the floating arrow to create them.

**Comment by alderg** [comment] 2024-09-06 12:58
Duplicate of https://github.com/jgraph/drawio/issues/4130

**Closed by alderg** 2024-09-06 12:58 UTC

**Comment by deadlyBuzz** [comment] 2024-09-06 14:08
Thank you.  I would never have thought of searching for "Picker" for the control.  I did search for it.
