### ISSUE TITLE
Shadow is not exported in PDF when View > Shadows is ticked and shadow option under Diagram tab

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1789] opened 2021-02-01 12:53 UTC
When a shadow option is ticked in Diagram tab (when no shape is selected), shadow isn't exported in PDF. 
The same issue appears when View > Shadows (we said it will be fixed in 2017 https://github.com/jgraph/drawio/issues/86 - Connect to preview )

When a shape is selected and shadow ticked in Style tab, shadow is exported in PDF. 

Tested in diagrams.net 14.2.9 and Chrome Incognito with File > Export as > PDF and File > Export as > Advanced > PDF

 https://drawio.atlassian.net/browse/DND-86

**Comment by davidjgraph** [comment] 2021-02-01 13:13
Duplicate of #86

**Closed** 2021-02-01 13:13 UTC
Labels: bug
