### ISSUE TITLE
[Feature] EPS figure 

### ISSUE THREAD

**Issue by yuanjiechen** [jgraph/drawio#2124] opened 2021-07-05 05:44 UTC
Is it possible to add feature for supporting to export EPS figure ?

**Comment by davidjgraph** [comment] 2021-07-05 06:42
Duplicate of #1540 . Please search before posting in future.

**Closed by davidjgraph** 2021-07-05 06:42 UTC

**Comment by YalandHong** [comment] 2022-10-26 12:00
#1540 has been closed without fixing. Please consider re-opening either #1540 or this issue. Thanks!
