### ISSUE TITLE
Integrate OSX file associations with app

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#206] opened 2018-01-16 19:11 UTC
When I double click on a draw.io compatible file on my local filesystem, I would like it to open in the app.  Right now I have to launch the app, then open the file from the app.

**Comment by alderg** [comment] 2018-01-17 08:32
Duplicate of https://github.com/jgraph/drawio/issues/152

**Closed by alderg** 2018-01-17 08:32 UTC
