### ISSUE TITLE
Merge or split cells in a table

### ISSUE THREAD

**Issue by faea726** [jgraph/drawio#2155] opened 2021-07-21 19:03 UTC
Sometimes, I want to make a table with mixed cells (as attached image). That required feature to merge/split cells.
I usually use rectangle shapes to cover cells, to get a result like those cells are merged.
But it's not dynamic and looks bad.
It's will be nice if we have ability to merge/split cells (like merge feature of excel)
![Untitled](https://user-images.githubusercontent.com/37011495/126545005-63ff4623-2cc7-486e-ac16-b16ec39fc3ff.png)

**Comment by davidjgraph** [comment] 2021-07-21 20:51
Duplicate of #979

**Closed by davidjgraph** 2021-07-21 20:51 UTC
