### ISSUE TITLE
"Paste and match style" feature

### ISSUE THREAD

**Issue by pertoft** [jgraph/drawio#3358] opened 2023-02-15 07:56 UTC
**Describe the solution you'd like**
Many program as a feature to paste text without formatting called "paste and match style"

It would be very nice to have a feature in draw.io, where text copied to clipboard can be pasted without any formatting.

**Comment by alderg** [comment] 2023-02-18 06:40
Duplicate of https://github.com/jgraph/drawio/issues/291

**Closed** 2023-02-20 09:16 UTC
Labels: wontfix, Issue template not filled, low quality
