### ISSUE TITLE
Open from Github - Repository not found

### ISSUE THREAD

**Issue by xundong** [jgraph/drawio#3400] opened 2023-03-03 09:00 UTC
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Open from Github can't see my the main branch on my Github repository where I saved all my drawing files.
Instead, it returns "Repository not found" in the Select File prompt

**To Reproduce**
1. Go to draw.io web browser, click on start button, app.diagrams.net loads in a new tab.
2. Click on Open File from Github, Authorise with Github, then click on open existing diagram, "Select File" prompt appears with my repository listed
3. Double click on my drawing repository, "Repository not found" message appears in the Select File prompt.

**Expected behavior**
A list of all of my save drawings file save in that github repository.

**Screenshots**
Select File prompt
![image](https://user-images.githubusercontent.com/33489013/222675480-4c638691-ebcc-4ec4-99f3-cc511fdeaa0c.png)
Draw.io app configurations
![image](https://user-images.githubusercontent.com/33489013/222675806-fff4fa3c-5fab-40a9-a5d6-a2118ae6c9bf.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
21.0.1
**Desktop (please complete the following information):**
- OS Windows 11 22H2 with 2023-02 CU
 - Browser Firefox 
 - Version 110.0.1
 - Edge
 - Version 110.01587.63

**Additional context**
So far I have tried clearing all browser cache as well as removing all saved web and windows credentials.

**Comment by alderg** [comment] 2023-03-03 09:17
Duplicate of https://github.com/jgraph/drawio/issues/3396

**Closed** 2023-09-15 16:09 UTC
