### ISSUE TITLE
add reference line

### ISSUE THREAD

**Issue by cmdares** [jgraph/drawio#2913] opened 2022-07-02 14:52 UTC
[X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
[X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
Is your feature request related to a problem? Please describe.
no

Describe the solution you'd like
Add Reference line of drawing software such as Photoshop

Describe alternatives you've considered

The reference line and auxiliary line have their own application scenarios
Guides can prompt lines to align surrounding objects when dragging objects with the mouse.
The reference line will appear in common design graphics software, such as PS, Visio, etc.
For example, I need to design a fixed scale drawing of the project. I need to design the overall skeleton according to the specified size in advance. Some fixed boundaries will be designed in advance. I will use reference lines to divide them in advance. When designing the drawing, it is conducive to the accurate placement of elements.
![image](https://user-images.githubusercontent.com/5292190/177005597-53251c5f-fddb-4745-937b-fbac85136c87.png)

**Comment by davidjgraph** [comment] 2022-07-02 18:17
OK, this is too much, you're banned for breach of the code of conduct. Duplicate of #2644

**Closed by davidjgraph** 2022-07-02 18:17 UTC
