### ISSUE TITLE
Additional/incorrect characters in gitlab wiki integration SVGs

### ISSUE THREAD

**Issue by OleBae** [jgraph/drawio#3562] opened 2023-05-04 10:10 UTC
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We have an on-site gitlab instance (gitlab 15.10.2) with draw.io wiki integration (21.2.6):
![image](https://user-images.githubusercontent.com/31850671/236166823-646c83f8-0ac3-488b-92c1-4b483aa44e64.png)

(As an aside I am very happy with how well draw.io works with gitlab!)

As seen above the note looks just fine in the editor, but in the gitlab SVG there is some extra characters:
![image](https://user-images.githubusercontent.com/31850671/236167742-0c2b2526-34fe-4b1e-a59e-58b0d794c1d8.png) (screenshot of the wiki page; the svg itself is attached below.

The first line is "hi!<line-break>" and looks fine, while the second line is "hello!<space><line-break>" and gets a "bonus" Â character.  The € character is just a mess.

If I from the gitlab integrated editor do export to svg, the svg content looks fine, so something different happens at "Save & Exit" than at "Export to SVG"(?)

Attached is: 

 
![test drawio (1)](https://user-images.githubusercontent.com/31850671/236174651-74b51a23-df4b-4468-b98e-f24401e842f6.svg) -  the svg created by "Save & Exit" 

![test-exported drawio](https://user-images.githubusercontent.com/31850671/236171066-12280313-d970-4971-9799-16ec0be1a9e6.svg) - identical draw.io content as above, but export to svg from editor menu

[test.drawio.xml.zip](https://github.com/jgraph/drawio/files/11396192/test.drawio.xml.zip) - same content with export as xml

- draw.io version [e.g. 21.2.6] 
- in on-site gitlab 

**Desktop (please complete the following information):**
On windows desktop with recent/latest Chrome and Edge

**Comment by m-mohamedin** [comment] 2023-05-04 21:48
Thanks for the report. The problem is in gitlab code.

Please open a ticket there with the following information

In file gitlab/app/assets/javascripts/drawio/drawio_editor.js
function getSvg(data)
The base64 svg data is decoded using 
`const svgPath = atob(data.substring(data.indexOf(',') + 1));`

It should be:
`const svgPath = decodeURIComponent(escape(atob(data.substring(data.indexOf(',') + 1))));`

The reason is atob native JS function doesn't work well with Unicode characters

Thanks

**Comment by davidjgraph** [comment] 2023-09-15 15:57
Closing as duplicate of https://gitlab.com/gitlab-org/gitlab/-/issues/410103

**Closed by davidjgraph** 2023-09-15 15:57 UTC
