### ISSUE TITLE
Search term written in reverse after existing text is selected from right to left with the mouse in Search Shapes box.

### ISSUE THREAD

**Issue by crosscode-nl** [jgraph/drawio#1740] opened 2021-01-04 10:43 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Searching in Search Shapes writes the search term in reverse after existing text is selected from right to left with the mouse most of the times. When I type User it will becom resU. 

**To Reproduce**
1. Enter some text in Search Shapes box. I.E. User
2. Select text 'User' from right to left with the mouse, so it is highlighted.
3. Enter some text, which will now replace the old text as expected, but will be written in reverse 'resU`. - ERROR

**Expected behavior**
I expect the text to be replaced and the new text to be written from left to right.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.1.5 

**Desktop (please complete the following information):**
 - Linux Debian 10
 - Chrome 
 - 87.0.4280.88

**Comment by ashrafteleb** [comment] 2021-01-07 19:40
Unfortunately we couldn't reproduce. Can you send us a video?
Also, what is the desktop environment used?

**Comment by crosscode-nl** [comment] 2021-01-09 15:43
It happened on Debian 10 under VMWare. Currently I can't reproduce it either. It happened under Chrome as well as using the desktop application. 

Investigating the issue further I think this is Chromium related: https://bugs.chromium.org/p/chromium/issues/detail?id=932002

So I guess you can't do a lot about it.

**Comment by ashrafteleb** [comment] 2021-01-10 17:00
Thanks for your reply. I'll close the issue and hopefully Chromium will fix it

**Closed by ashrafteleb** 2021-01-10 17:00 UTC
Labels: Waiting for response
