### ISSUE TITLE
Unable to use "m+" font as custom font

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#459] opened 2019-06-17 12:39 UTC
https://mplus-fonts.osdn.jp/about-en.html

User has it installed locally, but unable to reference in custom font dialog.

Tried using "Arial" and "Arial Narrow", that produces correct narrow font for second, so more likely the plus causing problems, rather than the space.

**Comment by RickCogley** [comment] 2019-06-19 04:17
Here's a screenshot of what the font is supposed to look like, and test text:

日本語 1234567890 いろはにほへとちりぬるを わかよたれそつねならむ うゐのおくやまけふこえて あさきゆめみしゑひもせす

<img width="1481" alt="JRC Screenshot 2019-06-19 at 13 08 26" src="https://user-images.githubusercontent.com/512328/59736414-7c50dc80-9294-11e9-8318-26b82a3ca0ac.png">

**Comment by RickCogley** [comment] 2019-06-19 04:25
Ok, interestingly enough, when I set "M+ 1p" now, with the quotes, it does work, where the other day it did not. It is possible that disabling and reenabling the font on my system caused something to start working, if your side has not actually tried fixing it yet. I looked at my font explorer the other day and confirmed it was enabled before the test, but today I purposefully dis- then re-enabled the font. 

That said, it does not export to PDF.

**Comment by RickCogley** [comment] 2019-06-19 04:28
Exports to JPG and PNG _do_ work. 

<img width="1913" alt="JRC Screenshot 2019-06-19 at 13 28 08" src="https://user-images.githubusercontent.com/512328/59736831-28df8e00-9296-11e9-8e81-e47a61cb48cd.png">

**Comment by davidjgraph** [comment] 2019-06-27 10:01
If you use Print and save as PDF, either using the built-in PDF on Chrome or Mac, does that output the font correctly?

**Comment by RickCogley** [comment] 2019-06-27 11:58
Yep, just the std cmd-p followed by selecting PDF in the OS dialog box works: 

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/512328/60264453-2fb57300-991e-11e9-8fad-3bf89524be4d.png">

**Comment by davidjgraph** [comment] 2019-06-27 11:59
If the output is good enough, that's probably my preferred route for custom fonts. I know we used to have m+ on the old image servers, but there are considerable more now and setup isn't fully automated (due to them being MacOS), someone who have to add the font to every server (for every font)....

**Comment by RickCogley** [comment] 2019-06-27 12:01
it's good enough, David, for sure. A problem I just noticed FYI is, when I do this process, even though I set portrait everywhere, the file is set to landscape. Maybe that is a firefox thing, so when I have time I will try other browsers.

**Comment by RickCogley** [comment] 2019-06-27 12:03
ah, never mind. That is an artifact of how Preview.app presents it. There is no border until you zoom out, and it looks like landscape. Sorry, it's no problem.

**Comment by RickCogley** [comment] 2019-06-27 12:07
Can the HTML entities that get substituted in for the double quotes be fixed, in the dropdown display? 

<img width="388" alt="image" src="https://user-images.githubusercontent.com/512328/60265017-8b343080-991f-11e9-958c-7c97d1ae24ab.png">

**Comment by alderg** [comment] 2019-06-27 14:11
Fixed in 10.8.2.

**Closed by alderg** 2019-06-27 14:11 UTC
Labels: bug

**Comment by alderg** [comment] 2019-06-28 11:36
Fixed in 10.8.3.

**Comment by RickCogley** [comment] 2019-06-28 21:39
Confirmed @alderg; thanks very much!

**Comment by davidjgraph** [comment] 2019-07-31 08:33
This causes a serious regression in the core, https://github.com/jgraph/mxgraph/issues/351, so we're going to have to revert this one.

If you ever meet the folks who created this font, my hint is never, never put a plus sign in a font family name...
