### ISSUE TITLE
Neither ctrl-c nor ctrl-v works on objects

### ISSUE THREAD

**Issue by reece** [jgraph/drawio#2523] opened 2022-01-04 16:28 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Ctrl-C and Ctrl-V do not work to copy and paste objects. The Copy and Paste menu items work fine for the same objects. Ctrl-C and Ctrl-V *do* work when copy/pasting selected text within objects, but not the objects themselves.

**To Reproduce**
1. Open Chrome 96.0.4664.110 on Linux. Create a new incognito window. Open app.diagrams.net. "Decide later" about where to save diagrams.
2. Create a plain rectangle. Select the object. Select Edit > Copy, deselect the object, then Edit > Paste. A new rectangle should appear, demonstrating that copy-paste works. 
3. Create a new rectangle and color it (to differentiate from the previous object). Press Ctrl-C, then select Edit > Paste. The first (uncolored) rectangle is pasted. Ctrl-C didn't copy the colored rectangle.
4. Copy the colored rectangle with Edit > Copy, then press Ctrl-V. Nothing is pasted. Ctrl-V doesn't work.

**Expected behavior**
I expect that Ctrl-C and Ctrl-V work as shortcuts for copy and paste respectively, consistent with nearly all other apps and web apps, including similar object drawing apps like Google Slides and Google Diagrams that run in Chrome.

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.2.0

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 96.0.4664.110

**Additional context**
Note that the reproduction was in an incognito window.

I'm happy to engage in testing if that's useful. Thanks for diagrams.net.

**Comment by reece** [comment] 2022-01-04 17:57
Follow-up: Firefox 95.0.2 exhibits identical behavior.

**Comment by mararad** [comment] 2022-01-05 10:48
Could you check if a new rectangle appears on the top of original one, please? Pasted shape can fully cover the original shape in some cases so it looks like only one shape is there.

* If you select a rectangle, click Ctrl+c and then Ctrl+v while still selected, is copy/paste working?

* If you select a rectangle, click Ctrl+c and then right mouse button > Paste here, is it working?

**Comment by reece** [comment] 2022-01-06 06:46
> - If you select a rectangle, click Ctrl+c and then Ctrl+v while still selected, is copy/paste working?

It is not working. No new shape is created as tested by moving the selected shape. (Also, this is consistent with the original post in which I created a colored rectangle, copied it with the menu, and pasted with Ctrl-V; if the shortcut had worked, I would have seen a colored rectangle.)

> - If you select a rectangle, click Ctrl+c and then right mouse button > Paste here, is it working?

No, it's not working. (Also, again I think the original post covers this case using colored rectangles as a way to test which object is copied or pasted, if any.)

**Comment by reece** [comment] 2022-05-18 21:42
Is there any update on this?

I'm using draw.io 18.0.2 and the copy paste shortcuts are still non-functional.

**Comment by jehannon** [comment] 2022-06-12 04:24
I just tried both the 19.0.3 AppImage and *.deb on Ubuntu 20.04. 

Copy/Paste ctrl-c and ctrl-v still not working.

**Comment by JonathanTSilva** [comment] 2022-11-30 17:42
I've tested this feature (copy/paste with keyboard shortcuts) in Pop!_OS 22.04 LTS with a flatpak installation, and it still doesn't work.

**Comment by olddesklamp** [comment] 2023-01-30 01:26
Ditto to the above, although strangely right ctrl works but not left ctrl. Maybe the fix is as simple as changing the keybindings?

**Comment by kaustubhcs** [comment] 2023-03-09 16:51
Using the Drawio version
```
diagrams.net 20.8.16
```
Same issue. If you right-click "Copy" and then right-click "Paste Here"; it works
But `Ctrl - C` `Ctrl - V` does not work

OS Versions: `Ubuntu 20.04.4 LTS`

**Comment by terence4444** [comment] 2023-04-29 09:41
same issue with draw.io flatpak 21.1.2 on Linux Mint 21.1 Cinnamon

`Linux version 5.15.0-71-generic (buildd@lcy02-amd64-044) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023`

**Comment by epoiate** [comment] 2023-08-21 13:12
Same issue. `Ctrl-X` doesn't work too.

OS: Ubuntu 22.04.03 (LTS)
Browser: Chrome 116.0.5845.96
diagrams.net: v21.6.8

**Comment by JamesO2x** [comment] 2023-10-02 22:33
I'm experiencing the same issue on the Windows desktop release. I was running version 22.0.1, I did some quick edits to a file, then updated to version 22.0.1. Now CTRL + C/X/V doesn't work on objects. I can confirm these commands were working before the update. Using `Edit -> Copy` and such GUI commands work fine though. Its just the keyboard shortcuts that don't.

I just downgraded to version 22.0.0 and the CTRL + C/X/V commands work again.

**Comment by Deep-RI** [comment] 2023-10-05 08:42
I am also experiancing the same problem with 22.0.1. Ctrl-C / V has stopped working but right click and select copy and paste works fine.

**Comment by alderg** [comment] 2023-10-05 11:10
Fixed in v22.0.2. To update: Close all tabs, go to https://app.diagrams.net/clear.html reload the app.

**Comment by Sharpiro** [comment] 2023-11-23 04:34
just tried out this app for the first time.  my ctrl-c works, my ctrl-v doesn't.  I use Linux and have caps lock remapped as ctrl, and have never seen an app behave differently toward it until now.  My normal ctrl-v with the real control key works, the ctrl-v with the capslock key does not.

**Comment by mlzxy** [comment] 2024-01-16 00:53
Using ubuntu 20.04 and diagrams.net 22.1.18, ctrl+v does not work (try clear cache but still)

**Comment by davidjgraph** [comment] 2024-01-29 14:01
This issue is resolved for draw.io and the deployment at app.diagrams.net. If you have a case with the desktop, please file that on the desktop project with full details. https://github.com/jgraph/drawio-desktop/issues

**Closed by davidjgraph** 2024-01-29 14:01 UTC
Labels: help wanted, blocked/need-repo
