### ISSUE TITLE
New AWS Service Icons

### ISSUE THREAD

**Issue by be-meyer** [jgraph/drawio#3753] opened 2023-07-31 06:32 UTC
There has been a new AWS Icon package released which removed the gradient from the Icons backgrounds. 

The icons can be found here: https://aws.amazon.com/architecture/icons/
Asset package: https://d1.awsstatic.com/webteam/architecture-icons/q2-2023/Asset-Package_04282023.ca9655a386a46bda0b6238cca2651e8f27fcb5c9.zip

I'd appreciate updating the current icons to it.

**Comment by davidjgraph** [comment] 2023-07-31 07:54
This seem like duplicate of #3677

**Closed** 2023-07-31 10:07 UTC
