### ISSUE TITLE
Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by editor37** [jgraph/drawio#3917] opened 2023-10-08 18:17 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Error while accessing the page. app's running in container. Tried different servers and types (Synology built in docker, container inside (debian/ubuntu) linux VM, proxmox lxc )
"Failed to execute 'open' on 'XMLHttpRequest': Invalid URL"
New install, old install, different clients with chrome/firefox/edge, Windows/Linux/Android - situation is the same. 
Old one (deployed several months ago worked without any problems. But now it has the same problem as new one)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Comment by lixiaofei123** [comment] 2023-10-09 02:48
Maybe adding offline=1 to the url can help you.
For example
https://example.com?offline=1

**Comment by editor37** [comment] 2023-10-09 09:50
You're right, it helps. Thanks for the suggestion!
But I've a question. I've never used "offline=1" before, it worked without one like a charm.
I don't have any port restrictions for this container; at this moment, it has "any any" access (because of troubleshooting) to the internet. (Even I'm going to use it locally only later, without internet.)
Is this a client/browser kind of problem or restriction that I've to dig at my side, or is it some intermediate app issue that will be resolved later?

**Comment by alfred-nice** [comment] 2023-10-09 14:24
i have the same question. thx!

**Comment by InRiPa** [comment] 2023-10-10 09:06
Same issue: Adding `offline=1` seems to have worked. I'm not sure how to reproduce this. Sometimes, it's needed and sometimes it just works. I think it's related to the image, since the older image `82abb4be3093` works constantly.

**Comment by Eyeanman** [comment] 2023-10-17 08:16
Chipping in as also getting the error

Console output:
`content.js:33 Uncaught (in promise) Error: Illegal argument undefined
    at e.exports (content.js:33:95534)
    at content.js:73:1527543
    at p (content.js:73:185751)
    at Generator._invoke (content.js:73:185504)
    at Generator.next (content.js:73:186114)
    at r (content.js:73:192157)
    at s (content.js:73:192360)
e.exports @ content.js:33
(anonymous) @ content.js:73
p @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:73
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:73
H$ @ content.js:73
W$ @ content.js:73
(anonymous) @ content.js:73
p @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:73
r @ content.js:73
s @ content.js:73
Promise.then (async)
r @ content.js:73
s @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:73
T.emit @ content.js:3
value @ content.js:1
(anonymous) @ content.js:1
p @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:73
r @ content.js:73
s @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:73
(anonymous) @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:73
Show 49 more frames
Show less
app.min.js:11856 SEVERE Failed to execute 'open' on 'XMLHttpRequest': Invalid URL null null null DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at mxXmlRequest.send (https://draw.MYDOMAIN.com/js/app.min.js:287:245)
    at Object.get (https://draw.MYDOMAIN.com/js/app.min.js:199:292)
    at App.fetchAndShowNotification (https://draw.MYDOMAIN.com/js/app.min.js:13059:32)
    at App.updateButtonContainer (https://draw.MYDOMAIN.com/js/app.min.js:13056:297)
    at EditorUi.updateUi (https://draw.MYDOMAIN.com/js/app.min.js:12366:119)
    at new App (https://draw.MYDOMAIN.com/js/app.min.js:12878:357)
    at g (https://draw.MYDOMAIN.com/js/app.min.js:12893:267)
    at https://draw.MYDOMAIN.com/js/app.min.js:12884:121
    at s.onload.s.onreadystatechange (https://draw.MYDOMAIN.com/:173:13)`

**Comment by OrcD3vil** [comment] 2023-10-18 06:29
Having the same issue as the above.
[drawio_drawio-55cc549cc5-47wt9_drawio.log](https://github.com/jgraph/drawio/files/12993905/drawio_drawio-55cc549cc5-47wt9_drawio.log)


TrueNAS Version: TrueNAS-SCALE-22.12.4.1
TrueCharts App Version: drawio 22.0.3_6.0.12

This is a fresh install of the app and when navigating to the website it gives the error:  Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

When adding "?offline=1" then it allows the app to work for some reason.  I have attached the logfile to this post.

**Comment by yiunam126** [comment] 2023-10-23 02:57
Same problem in here after update from v21.8.2 to v22.0.6
Running from docker container in a synology nas with the buildin reverse proxy

**Comment by davidjgraph** [comment] 2024-03-13 10:07
Closing, not clear what the environment is here.

**Closed by davidjgraph** 2024-03-13 10:07 UTC
Labels: huh?
