### ISSUE TITLE
Command key related shortcut doesn't work if using an external keyboard, and swap the "command" and "option" key

### ISSUE THREAD

**Issue by matrixhcl** [jgraph/drawio#606] opened 2019-10-18 08:33 UTC
**Environment**
MacOS 10.14.6, draw.io cloud 12.1.2

**Issue Details**
An external keyboard, which is a standard windows keyboard, is connected to my macbook.
I swap the "command" and "option" key with macOS build-in setting, which could be found at System Preferences -> Keyboard -> Modifier Keys, so I could execute "command" related shortcut like copy & paste with pressing the "Alt" key on the external keyboard. It works fine on all kinds of application (e.g. photoshop, chrome), except on draw.io cloud.

**Comment by copejon** [comment] 2020-04-20 14:52
I'm seeing this as well on.

 **Environment**
MacOS 10.14.6 
Draw.io Cloud 12.9.14
Swapped Cmd and Opt keys on an external keyboard

**Details**
This behavior is not reproduced on firefox 75.0 so it may just be limited to chrome.

Reverting the keyboard to default fixes the issue, but it is cumbersome.  The original mappings are not the aligned to the mac keyboard, hence the need to swap them.

**Comment by valbaca** [comment] 2020-07-08 19:45
I'm also seeing this issue on Chrome and Safari. I have similar modifier key remappings via System Preferences. No repro on Firefox. 

MacOS 10.14.6 (18G3020)

One helpful workaround is to use the "Duplicate" shortcut (Cmd+d), which does work.

**Comment by copejon** [comment] 2020-07-09 14:41
I'll add the workaround I've found as well: select the item or group of items, then hold cmd and click and drag the selected item(s).  This produces a dupe of the selected items(s) automatically being dragged by the cursor.  So at least there's more than one option here.

**Comment by meteozond** [comment] 2020-07-29 05:52
Another workaround is using [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements)  keyboard customization tool. 
![image](https://user-images.githubusercontent.com/975689/88761868-ad2e6100-d178-11ea-9efe-eb488bd35ba0.png)

**Closed** 2020-11-28 15:27 UTC
Labels: wontfix
