### ISSUE TITLE
Text Padding & Auto Resizing of Text Containers

### ISSUE THREAD

**Issue by ironlion37** [jgraph/drawio#2856] opened 2022-06-05 18:57 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm frustrated that I have to spend time resizing diagram boxes after entering text, and that they don't automatically resize.

**Describe the solution you'd like**
I would like topic containers (squares, rectangles, etc..) to automatically resize after text is entered. And I'd like there to be a padding setting that can maintain padding between the text and the edge lines of its container. This helps to maintain an uncluttered presentation in the diagram.

**Describe alternatives you've considered**
I am not aware of any alternative solutions. I tried adding a padding value to container styles and that didn't work. Under the "Property" section, there is something called "Label Padding." I tried adjusting that and couldn't see any effect.

**Additional context**

**Comment by ironlion37** [comment] 2022-06-06 18:55
Hi, I've corrected the formatting of my post. Do I need to resubmit as a freshly posted issue?

**Comment by mawid6** [comment] 2022-06-07 18:31
We meet again @ironlion37! :-) 

Padding can be set in the properties panel. Text tab, "Spacing" section. Atleast, I think that might be what you are after. Play with those values.

As for getting the shape to expand its height, to get the text to fit, I am not sure if that can be done. You can autosize, but I have not managed to get it to work for a note, it just expands the width... So, stumped on that one. :) Hope someone from diagrams.net can shed some light on it...

**Comment by ironlion37** [comment] 2022-06-07 21:40
Thanks @mawid6 again for the assist! Global spacing on the text tab is what I was looking for. Very nice. I'll leave this open a bit longer in case anyone has any input on autosizing the box after text is entered.

**Comment by mawid6** [comment] 2022-06-08 10:11
I have felt the need for autosizing the height of text containers before, and so have others - there is a request for this here: #2732

(Go in and like that issue).

If you agree, this can be closed as a duplicate of that issue.

**Closed** 2022-06-08 14:42 UTC
