### ISSUE TITLE
Mathematical formula's disappear on zoom levels other then 100%

### ISSUE THREAD

**Issue by casperlamboo** [jgraph/drawio#1213] opened 2020-10-03 13:28 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Some of the Latex formulas are not visible on zoom levels other than 100%.

This does not happen with all formula's but only these two particular formulas on the bottom of the page.

**To Reproduce**
Download the following file [Summary2.drawio.zip](https://github.com/jgraph/drawio/files/5321727/Summary2.drawio.zip) and load it into the drawio workspace. When zooming in and out the formulas appear and disappear

**Expected behavior**
Formula's stay visible on any zoom level

**Screenshots**
<img width="1712" alt="Schermafbeelding 2020-10-03 om 15 19 23" src="https://user-images.githubusercontent.com/6638028/94992683-ff7e6a80-058b-11eb-974b-e8b78ee8291d.png">
<img width="1712" alt="Schermafbeelding 2020-10-03 om 15 19 10" src="https://user-images.githubusercontent.com/6638028/94992695-086f3c00-058c-11eb-82cb-8cc42c33501c.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [13.7.3]

**Desktop (please complete the following information):**
Tested on desktop app OS X Catalina v10.15.7 and on the web-app in chrome

**Comment by mararad** [comment] 2020-10-05 08:47
Hi,

I reproduced this in Chrome and Chrome Incognito with diagrams.net version 13.7.7 and in desktop 13.7.3 on Win10 when zoom in/out is used via:
* Ctrl+mouse wheel
* zoom in/out icon 
* zoom number changed in the toolbar

In Firefox 81.0 (64-bit) it is working well. Is it possible to check FF and tell me the result, please?

Thanks,

**Comment by casperlamboo** [comment] 2020-10-05 08:57
Tested on firefox v81.0.1, without any issues. All formula's are visible on any zoom level as expected.

**Comment by casperlamboo** [comment] 2020-10-05 09:01
I did notice that latex formula's within the `$$ [[[LaTeX]]] $$` notation do have this issue while formula's within the `\( [[[LaTeX ]]] \)` do not have this issue.

**Comment by alderg** [comment] 2020-10-07 07:27
This seems to be a bug in Chrome. However, we were able to find a workaround by overriding position: relative with position: static for block elements (ie. div.MathJax_SVG_Display { position: static !important; }) which seems to be valid as relative elements seem to use the default position (ie the same as static).

**Comment by casperlamboo** [comment] 2021-01-04 14:11
With the most recent version of draw.io (v14.1.8) this bug seems to be occurring again. This time it is a bit harder to reproduce. In the example attached are three text fields, all containing some latex notation. One the the textfields disappears on any zoom level other then 100%.

tested on
Desktop client (MacOS): can reproduce bug
Chrome : can reproduce bug
FireFox: **cannot** reproduce bug

[error.drawio.zip](https://github.com/jgraph/drawio/files/5765042/error.drawio.zip)

**Comment by alderg** [comment] 2021-01-13 07:42
Thanks for the report. This will be fixed in the next release.

**Closed by alderg** 2021-01-13 07:42 UTC

**Comment by jkomyno** [comment] 2021-07-08 22:43
It is occurring again

**Comment by alderg** [comment] 2021-07-12 08:59
What browser, version and operating system?
