### ISSUE TITLE
to have working internal links when exporting to PDF.

### ISSUE THREAD

**Issue by wellbeingtool** [jgraph/drawio#1110] opened 2020-08-13 08:32 UTC
* [ YES] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Yes] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When exporting long documents that is full of charts about different points, it's always painful not to have internal linking between those different parts to make transition easier, like in a long course where you can link between one part of a general chart to another detailed chart for a different chapter.
This is already a feature in program like PPT where you can link between 1st slide and the 4th one and it still is working when exporting to PDF

**Describe the solution you'd like**
To have the linking between different pages work even after exporting to PDF

**Describe alternatives you've considered**
To create the whole project in PPT as I can link between one part of the chart to another entire chart in another page to make it easier for audience navigating a long course. The disadvantage I will face is the hard time creating the charts as it's not the same easier and better experience I had from draw.io

**Additional context**
Attached is an example for the problem I have. I am designing a course using charts and I want to be able to link between the word/shape "Analyze" from the "general" image to the whole page that contains the "analyze" chart. It works on draw.io program when linking between the shape "analyze" in the "general" page to the page that contains the "analyze" chart. But it's not working when exporting to PDF
![General](https://user-images.githubusercontent.com/69346569/90111906-975f9500-dd4f-11ea-8621-48679772687e.png)
![Analyze](https://user-images.githubusercontent.com/69346569/90111918-9a5a8580-dd4f-11ea-9429-8ebd95f59157.png)

**Comment by davidjgraph** [comment] 2020-08-13 08:34
Duplicate of #722

**Closed by davidjgraph** 2020-08-13 08:34 UTC
