### ISSUE TITLE
Name of shapes

### ISSUE THREAD

**Issue by Bruneux** [jgraph/drawio#401] opened 2019-03-19 21:50 UTC
Hi
Say you have received a diagram and want to know the name of certain shapes. Is there a way to know the name of the shapes in the diagram?
Thanks

**Comment by davidjgraph** [comment] 2019-03-21 14:19
Duplicate of https://groups.google.com/forum/#!topic/drawio/oPOMSQD5TPM

**Closed by davidjgraph** 2019-03-21 14:19 UTC

**Comment by Bruneux** [comment] 2019-03-22 00:17
Oh sorry, I thought the group was for questions / answers while github was for submitting a bug.

**Comment by davidjgraph** [comment] 2019-03-22 08:40
Github is for submitting bugs, but I don't see a bug report here.
