### ISSUE TITLE
WebKitBlobResource error on iPad Safari

### ISSUE THREAD

**Issue by my2iu** [jgraph/drawio#953] opened 2020-06-02 06:28 UTC
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Local file access doesn't work on Safari on iPad

**To Reproduce**
a) Saving a file to the device shows a WebKitBlobResource error. 
b) Opening a file from the device, brings up the file picker, but after choosing a file, the page reloads

**Expected behavior**
a) file should download
b) dialog box asking whether to open the file in a new window or the same window should show up

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari
 - Version 13.5

**Additional context**

https://github.com/jgraph/drawio/blob/65121dac0925f40dd9ffc69a053f38314043c0de/src/main/webapp/connect/confluence/config.js#L163-L166

Is it possible to increase the timeout before revoking the blob URL? Right now, it’s not possible to save documents locally on iOS because of a WebKitBlobResource error. I think other web apps have gotten around the issue by increasing the timeout enough so that users have time to select the file to download when Safari pops up a file screen, but I don’t know if that’s specifically what the issue is with draw.io.

**Comment by my2iu** [comment] 2020-06-03 19:58
After doing some testing, increasing the timeout to 10 or 20 seconds should give the UI and the user enough time to download the file.

Afterwards, there's a problem with opening files on Mobile Safari. It seems that altering the fields of the File Input causes Mobile Safari to reload the page (possibly due to a crash or something). It might be better to simply discard the old file Input element and just create a new one instead of reusing it. That would also solve the problem of getting change events even if the same file is reopened repeatedly.

https://github.com/jgraph/drawio/blob/b601c75cc98220e187e83f0797b01efadf06c6fe/src/main/webapp/js/diagramly/App.js#L3377-L3379

**Comment by alderg** [comment] 2020-06-09 11:28
Thanks for the report. This will be fixed in the next release. Please open a separate issue for the second bug with opening files. (We're currently unable to reproduce this when resuing the input element.)

**Closed by alderg** 2020-06-09 11:28 UTC
