### ISSUE TITLE
link advanced object to text file

### ISSUE THREAD

**Issue by fbalzarotti** [jgraph/drawio#2531] opened 2022-01-09 17:23 UTC
Insert any advanced object (text, mermaid, UML, SQL, CSV) with its content being read from a text file (e.g. in onedrive/etc.), instead of having to paste the code into a textbox.

This way, it would be possible to generate those advanced objects programmatically and have the diagram updated automatically.
This would be great especially for the CSV input.

**Comment by davidjgraph** [comment] 2022-01-09 20:42
CSV import is a duplicate of https://github.com/jgraph/drawio-desktop/issues/591 . Mermaid and PlantUML aren't core features, you would run those projects yourself to achieve that.

**Closed by davidjgraph** 2022-01-09 20:42 UTC
