### ISSUE TITLE
Import .svg file with utf-8 encoding issue

### ISSUE THREAD

**Issue by carusyte** [jgraph/drawio#172] opened 2017-11-10 05:31 UTC
I imported an utf-8 encoded .svg file but the canvas displays an object with a wrong encoding.
<img width="638" alt="screenshot" src="https://user-images.githubusercontent.com/1680881/32644296-96564b0c-c61b-11e7-8391-82f3da0ec5ee.png">

**Comment by alderg** [comment] 2017-11-10 19:02
Is this reproducible with https://www.draw.io? If yes, can you please include the SVG file for us to see what the problem is? If not, can you provide more information about the environment (browser, OS) and how you are running draw.io?

**Comment by carusyte** [comment] 2017-11-12 13:29
Yes, It is reproducible. I've prepared a desensitized version of the SVG file below. You can successfully view it in a functional text editor such as Sublime Text 3:
<img width="1198" alt="screen shot 2017-11-12 at 9 26 10 pm" src="https://user-images.githubusercontent.com/1680881/32699412-34981266-c7f0-11e7-9768-524727a56759.png">

But when I imported it into [https://www.draw.io]( https://www.draw.io):
<img width="399" alt="screen shot 2017-11-12 at 9 27 52 pm" src="https://user-images.githubusercontent.com/1680881/32699427-6ea9eaa6-c7f0-11e7-9a3a-52ce22d3ea76.png">

Here is the svg file:
[for_encoding_demo.svg.zip](https://github.com/jgraph/drawio/files/1464687/for_encoding_demo.svg.zip)

**Comment by alderg** [comment] 2017-11-15 08:49
Thanks for the report, this will be fixed in the next release.

**Closed by alderg** 2017-11-15 08:49 UTC
