### ISSUE TITLE
Google fonts on background page use alternate fonts on referring page

### ISSUE THREAD

**Issue by Garmatant** [jgraph/drawio#3281] opened 2023-01-11 22:00 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Using the feature where one page can be set as the background for another, I see that if the background page has text which uses a Google font, that font is changed to an alternate font on the page referencing it.

**To Reproduce**
1. Create a page called BG.
2. Drag out a text object from the shapes pane on the left.
3. In the Text tab in the right pane, set the Font to Helvetica.
4. Type HELLO WORLD to add that text to the text object.
5. Create a new page called PAGE 1.
6. In the diagram pane on the right, check the box next to Background, then click the Change... button.
7. In the page list dropdown, select the page called BG and press Apply.
8. See that your background on page PAGE 1 now shows the HELLO WORLD text in Helvetica.
9. Switch to the page called BG and select the text object.
10. In the Text tab on the right, open the Font dropdown and select Custom...
11. Under Google Fonts, type in Source Code Pro into the text box, or use any other valid Google font name and then click Apply.
12. Confirm you see the text object's font update.
13. Switch to the page called PAGE 1 and see that the font shows there as Times New Roman and not the correct Google font.

**Expected behavior**
The fonts used on the background page should look the same on any other page which uses that background page for its background.

**Screenshots**
![image](https://user-images.githubusercontent.com/64434341/211926008-0443be66-9a8f-4329-bbe4-6fc1f297a821.png)
![image](https://user-images.githubusercontent.com/64434341/211926117-a788cf6e-7fb2-476a-b55f-7f43b075bcb1.png)
![image](https://user-images.githubusercontent.com/64434341/211926255-85beecbf-c508-48cb-b121-564cb4174162.png)
![image](https://user-images.githubusercontent.com/64434341/211926336-91daab9e-582d-4e4c-af14-80b898d1307e.png)
![image](https://user-images.githubusercontent.com/64434341/211926396-6d85df78-33b1-455c-a8f8-007bd00563bf.png)
![image](https://user-images.githubusercontent.com/64434341/211926443-4af7479e-dd07-4147-8d22-ed7e5f7e55e4.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 20.7.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 108.0.1462.76

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a

**Additional context**

**Comment by alderg** [comment] 2023-01-12 05:55
Duplicate of https://github.com/jgraph/drawio/issues/2367

**Closed** 2024-02-02 02:38 UTC
Labels: wontfix
