### ISSUE TITLE
Z-order Forward and Backward

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1548] opened 2020-12-01 10:29 UTC
It would be great to reorder the object with "Forward" and "Backward" buttons instead of only "To Front" and "To Back".

Recent PowerPoint version has even a 3D vision of the different objects layers that makes it really intuitive (see the link below)

http://mybroadband.co.za/news/wp-content/uploads/PowerPoint_arrange_objects___scaled_351279731.jpg

**Comment by davidjgraph** [comment] 2021-01-21 10:25
Duplicate of #1103

**Closed by davidjgraph** 2021-01-21 10:25 UTC
Labels: feature request
