### ISSUE TITLE
Diagram starts to freeze when it gets larger

### ISSUE THREAD

**Issue by nikilthapa** [jgraph/drawio#3571] opened 2023-05-07 09:49 UTC
The drawio is an excellent tool. I really recommend and appreciate it. It has helped a lot in drawing many block diagrams, flowcharts, etc.  However, I am facing some annoying freezing issues. When I initially create new diagrams, it looks fine. I can quickly make diagrams.  But when my diagram gets larger, it starts to freeze and does not respond quickly. If I select or add or move blocks (rectangle, circle, etc...), draw lines, etc., the entire diagram freezes for 2 to 3 secs or more sometimes. It has reduced my productivity. I am still looking solution for such an issue. 
I am currently using the 21.2.9 version in Chrome browser (Version 105.0.5195.125). I used to sync up my design using Google Drive but later, I started to save on the local device. I thought it would solve the freezing issue but it is still right there.
I also followed this information https://www.drawio.com/blog/clear-diagrams-net-cache but still having the problem.

**Comment by davidjgraph** [comment] 2023-05-07 13:40
Browser extensions? System specifications? Diagram that recreates the problem?

**Comment by flybye97** [comment] 2023-05-09 10:08
CDMA

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by evlo** [comment] 2023-12-30 22:14
[exmple freezes.zip](https://github.com/jgraph/drawio/files/13799305/exmple.freezes.zip)

this is example of one of the smaller files with less freezing behaviour, some of the others I have are ie 6 pages and it is very frustraing. Sadly I still did not find any alterative do draw.io. This one is free to boot, so please do not take it as complaining, I'm rather looking for suggestions. 

_Ie. to not use pictures or make pictures much smaller before putting them to the diagram_

that i can do differently or even better for a way to get rid of the freezes while using the SW as it is now.

**Comment by LoftyLoftyLoftyLoftyLofty** [comment] 2024-02-28 07:19
Able to repro with this diagram:
https://drive.google.com/file/d/1ELjT0wOBBjzQXtIY8trRNmSLu-WMTH2G/view?usp=sharing

**Comment by davidjgraph** [comment] 2024-03-15 23:05
The issue is going to be autosave taking a long time because of the size of the diagram and/or the transmission speed of saving.

"exmple freezes" I cannot recreate the issue.

The last file on Google Drive, I can recreate. That's a 39MB file being saved repeatedly, yeah, that's going to be slow for most people. There is a very beta tool at https://github.com/jgraph/drawio/tree/dev/etc/imageResize. It performs resizing by image width value or image width percentage resizing.

You could add a console.log that tells you the size of each image, also.

**Comment by davidjgraph** [comment] 2024-03-23 22:28
We've an improvement in 24.1.0 specifically for diagrams with lots of images.

I'm going to close the issue up, as we might have a few issues tied into one in this thread. If you do still experience problems please open a new ticket with version, environment and sample diagram (i.e. follow the template).

**Closed by davidjgraph** 2024-03-23 22:28 UTC
Labels: blocked/need-repo
