### ISSUE TITLE
Can not save customized library anymore

### ISSUE THREAD

**Issue by Zonetech123** [jgraph/drawio#3323] opened 2023-01-30 17:22 UTC
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

ISSUE:
I can not save my customized library anymore. It used to work, but now when I add a new element on try to modify it, it shows saving and the wheel spins forever. 

1. Add new element to customized library (Drag and Drop)
2. Click on 'save' icon
3. wait forever

**Screenshots**
![2023-01-30 12_13_33-Hudson pompier Silverado drawio - diagrams net](https://user-images.githubusercontent.com/120660379/215548695-6ed174ec-c7a3-40f3-839c-1b12700ae307.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - Version [e.g. 20.8.10]

**Additional context**
Before, I had to save my work to be able to save modifications on library, but it does not work anyway

**Comment by alderg** [comment] 2023-01-31 12:06
Where is the library stored?

**Comment by Zonetech123** [comment] 2023-01-31 12:22
On a Onedrive account. And should it be .drawio or .xml?

De : Gaudenz Alder ***@***.***>
Envoyé : 31 janvier 2023 07:07
À : jgraph/drawio ***@***.***>
Cc : Samuel Viens ***@***.***>; Author ***@***.***>
Objet : Re: [jgraph/drawio] Can not save customized library anymore (Issue #3323)


Where is the library stored?

**Comment by alderg** [comment] 2023-01-31 12:27
.xml. Is there an error in the console?

**Comment by Zonetech123** [comment] 2023-01-31 12:31
Sorry what do you mean by ‘’console’’?

De : Gaudenz Alder ***@***.***>
Envoyé : 31 janvier 2023 07:27
À : jgraph/drawio ***@***.***>
Cc : Samuel Viens ***@***.***>; Author ***@***.***>
Objet : Re: [jgraph/drawio] Can not save customized library anymore (Issue #3323)


.xml. Is there an error in the console?

**Comment by alderg** [comment] 2023-01-31 12:32
https://balsamiq.com/support/faqs/browserconsole/

**Comment by Zonetech123** [comment] 2023-01-31 12:51
I dont use a browser to use the software. It was installed on the pc (Microsoft surface pro) via Microsoft store. There is no related error in Mozzila nor in Edge.

De : Gaudenz Alder ***@***.***>
Envoyé : 31 janvier 2023 07:33
À : jgraph/drawio ***@***.***>
Cc : Samuel Viens ***@***.***>; Author ***@***.***>
Objet : Re: [jgraph/drawio] Can not save customized library anymore (Issue #3323)


https://balsamiq.com/support/faqs/browserconsole/

**Comment by alderg** [comment] 2023-01-31 14:17
Thanks for the report. This will be fixed in the next release.

**Closed by alderg** 2023-01-31 14:17 UTC

**Comment by TechGeek01** [comment] 2023-04-13 02:42
Can confirm this is not fixed, and still has this issue on 21.1.2 on Windows 11 22H2 build 22621.1413

**Comment by alderg** [comment] 2023-04-14 08:59
We're unable to reproduce this error in Windows 22H2 build 22621.1413 and version 21.1.2. When we add a new item to a library we can save the changed library successfully. What are the exact steps to reproduce this error?

**Comment by TechGeek01** [comment] 2023-04-27 03:25
In my case at least, the issue isn't saving the library in the first place. Once a library is imported (or created), you can add shapes to it. The issue is that once the diagram file is saved, and the program is closed and reopened, when opening that diagram file, it loads the diagram and the libraries (I'm not sure if the imported diagrams are saved in the diagram file itself, or if the program just remembers which libraries I imported when I had that file open last), and when it auto-imports the libraries again, those auto-reimported libraries don't allow saving things. That is, you can drag and drop shapes to them, and the UI reflects that, but if you try and click on the edit button to rename a shape or something, and save the diagram file, it endlessly hangs with the spinning loading icon trying to save it.

In my case, trying to delete the library import with the X button doesn't work either, which is presumably related.

The thing I noticed that tells you whether it'll work or not is the library name. If I name a library, say, Logos, the library in the left bar is titled "Logos." However, when the program auto re-imports this when closing the program, and reopening the diagram, the name it's given is "Logos.xml" or "Logos.drawio" where the file extension is part of that displayed name. Whenever that's the case, that's when they bug out and do not work for me. That is, visually, the UI updates to reflect that I've dragged a shape to a library to add it, or it'll let me edit the library and rename or remove or re-order shapes, but when trying to save the library (when it is auto-imported and shows the file extension as part of the library name in the left pane), that's when this issue occurs, and saving said diagram is not possible.

**Comment by Zonetech123** [comment] 2023-05-01 11:56
Hi, the issue seems to be fixed. Everything works fine. Thanks you

De : Andy Yasger ***@***.***>
Envoyé : 12 avril 2023 22:43
À : jgraph/drawio ***@***.***>
Cc : Samuel Viens ***@***.***>; Author ***@***.***>
Objet : Re: [jgraph/drawio] Can not save customized library anymore (Issue #3323)


Can confirm this is not fixed, and still has this issue on 21.1.2 on Windows 11 22H2 build 22621.1413

**Comment by TechGeek01** [comment] 2023-05-02 04:14
This is not fixed for me on 21.2.1 on Win11 build 22621.1555. Clicking the +, edit, or close buttons on shape libraries that load with the diagram file (that is, ones that import automatically when you open the diagram file, not ones you manually import), still just expands or contracts the library, rather than the expected actions.

The expected actions work fine if the library is imported manually.
