### ISSUE TITLE
Export link to PDF

### ISSUE THREAD

**Issue by cinnagirl** [jgraph/drawio#3494] opened 2023-04-06 13:24 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Links (to another page) in draw.io are not available in a PDF export.

**Describe the solution you'd like**
Working (internal) links in PDF export. For example this does work very well in an PDF export from MS Office Visio.

**Describe alternatives you've considered**
Export to other formats such als PNG

**Comment by alderg** [comment] 2023-04-14 07:04
Support for links to pages was added in v21.1.6 for Print to PDF (via File -> Print, Save as PDF).

**Comment by alderg** [comment] 2024-04-14 08:54
Duplicate of #722

**Closed** 2024-04-14 20:00 UTC
Labels: duplicate
