### ISSUE TITLE
Uncaught DOMException: Failed to read the 'localStorage' in embed mode

### ISSUE THREAD

**Issue by atlemagnussen** [jgraph/drawio#2850] opened 2022-05-31 12:31 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I use embed.diagrams.net in my web page and noticed parts of the menu were missing in incognito mode.
app.diagrams.net works fine in incognito

So I found this error message in the console: 
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

**To Reproduce**
1. Need an implementation of embedded mode like your examples
2. Open it in incognito mode in Chrome

**Expected behavior**
I expect it to work even if incognito mode does not allow localstorage

**Screenshots**
When in incognito it is missing menu and exit button:
![diagramsnet-incognito](https://user-images.githubusercontent.com/1167660/171173388-4f28f6c3-94e9-4eeb-99f9-68aadcf1ceaa.png)

When in normal mode working:
![diagramsnet-normal](https://user-images.githubusercontent.com/1167660/171173473-e47daf2c-76d4-44c2-88c3-e677d8cc43b4.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 18.1.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 101.0.4951.67

**Comment by alderg** [comment] 2022-06-01 13:31
We're unable to reproduce this error. Could you provide a test case or a link to a test case. What is the full URL and stack associated with this error? (We used https://embed.diagrams.net/?spin=1&proto=json&libraries=1&configure=1 for testing.)

**Comment by atlemagnussen** [comment] 2022-06-07 13:13
The url to use is: `https://embed.diagrams.net?embed=1&proto=json&spin=1&saveAndExit=1&noSaveBtn=1&noExitBtn=0&ui=min&configure=1&dark=0&pv=0&lang=no`

If you need a full example I will provide

**Comment by atlemagnussen** [comment] 2022-06-07 14:20
Here is a full repro that produces the same error in incognito mode in Chrome:
`https://codepen.io/atlemagnussen/pen/zYRJEzW`

Using the same custom element as in my web app

**Comment by alderg** [comment] 2022-06-08 06:29
Thanks for the report. This will be fixed in the next release.

**Closed by alderg** 2022-06-08 06:29 UTC
