### ISSUE TITLE
Add/move/delete ports on SysML blocks

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2542] opened 2022-01-12 10:24 UTC
Asked in Discord 
"Some of the more complicated SysML symbols include ports. I’m looking for documentation that explains how to edit the number of ports, the labels, and the data flow direction."

At the moment editing the number of ports is not supported.

**Comment by davidjgraph** [comment] 2022-01-12 17:16
Duplicate of #864

**Closed by davidjgraph** 2022-01-12 17:16 UTC

**Comment by SebCanet** [comment] 2022-05-31 21:36
Hi,
I think it's not completed because it's not the same problem. What you are linking as duplicate is about contact point, to link boxes, the problem is the shape of the box.
What we need is add or delete ports on this kind of blocks:
![image](https://user-images.githubusercontent.com/6362199/171288187-bc33a41e-37f6-4e0a-a566-3e57654da59f.png)
Also change the port direction, the arrow and also the <> one.
