### ISSUE TITLE
Cannot change color of shape - "Cannot read properties of undefined (reading 'editor')"

### ISSUE THREAD

**Issue by faedrielle** [jgraph/drawio#3315] opened 2023-01-26 10:22 UTC
Hello,
thank you for making this awesome tool!

This worked for me yesterday, but doesn't today.

Steps:
1. Create a new drawio file on GDrive
2. Create a rectangle
3. Click on Fill color or Line color

Expected: Can change the color of the rectangle
Current: Cannot read properties of undefined (reading 'editor')

![image](https://user-images.githubusercontent.com/44054256/214812064-a51504b9-71d1-4089-85ac-0ec1eb33bb50.png)

**Comment by mararad** [comment] 2023-01-26 15:31
Hi,

I am not able to reproduce this in 20.8.11, Chrome Version 109.0.5414.76 (Official Build) (64-bit) and Win 10.

Do you have the same issue in other browsers and Incognito mode with all browser extensions temporarily disabled?
Does browser cache clear help?
Which diagrams.net version are you using? Can be seen under Help.
Which browser version and OS?
Do you have the issue with the diagram saved only in GDrive or in other storages also?

Thanks,

**Comment by faedrielle** [comment] 2023-01-26 16:11
diagrams.net version is 20.8.11

I'm on Chrome Version 109.0.5414.120 (Official Build) (64-bit) and Win 10.
Issue persists in Chrome incognito with no extensions, even if I choose "Decide later" for storage.
Here's a screen grab of the console 
![image](https://user-images.githubusercontent.com/44054256/214887689-3059d60f-dcef-4302-badd-734280ea87c3.png)


In Firefox 108.0.2 (64-bit) (both normal and incognito, storage set to "Decide later") the error changes:
![image](https://user-images.githubusercontent.com/44054256/214887918-ba494776-0c4d-4e2a-9817-65e33b89da3a.png)

**Comment by alderg** [comment] 2023-01-26 20:01
Thanks for the report. This will be fixed in the next release. As a workaround, set the colors via the Style format panel.

**Comment by davidjgraph** [comment] 2023-01-26 21:47
Internal commit https://github.com/jgraph/drawio-dev/commit/1662a7cc8c10aaf14f4aff1c44c411e0fb23b0e7
Internal release https://drawio.atlassian.net/projects/DS/versions/11258

**Comment by davidjgraph** [comment] 2023-01-26 22:09
Released in 20.8.13

**Closed by davidjgraph** 2023-01-26 22:09 UTC

**Comment by faedrielle** [comment] 2023-01-29 18:48
Great, it works, thanks for the quick fix!
