### ISSUE TITLE
Exporting as SVG converts SVG icons to bitmap

### ISSUE THREAD

**Issue by strate905** [jgraph/drawio#3651] opened 2023-06-07 08:43 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I import an SVG image from disk (or add an icon from a custom library of icons in SVG format.)
When I export the diagram as PDF, the SVG images/icons remain in vector format and I can zoom in without losing quality. However, when I export the diagram as SVG, the SVG images/icons are converted to bitmap and become pixelated when I zoom in.

**To Reproduce**
1. Create a library with at least one icon in SVG format.
2. Add the SVG icon from your created library to the drawing board. (Or simply import an SVG file into the drawing pad.)
3. Export the drawing to SVG format.
4. Zoom in to 200% or more; it shows that the icon has not been exported as a vector image.

**Expected behavior**
Exporting to SVG is expected to keep the icons in vector format, just like exporting to PDF does.

**Screenshots**
![Screenshot from 2023-06-07 11-34-27](https://github.com/jgraph/drawio/assets/58142069/705da8dc-ce6a-45f5-90f7-44caa83a0e3f)

**draw.io version (In the Help->About menu of the draw.io editor):**
- diagrams.net 21.2.8

**Desktop (please complete the following information):**
- OS: Fedora Linux 38

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alderg** [comment] 2023-06-07 08:44
Please attach a test case.

**Comment by strate905** [comment] 2023-06-07 08:55
Please find attached my compressed drawio file.
[svg-export-test.zip](https://github.com/jgraph/drawio/files/11674737/svg-export-test.zip)

On a side note, I just confirmed that exporting my drawing as SVG works perfectly when using https://app.diagrams.net/

**Comment by alderg** [comment] 2023-06-07 12:49
So you are using the desktop app?

**Comment by strate905** [comment] 2023-06-07 13:07
I am using the GNOME image viewer to open SVG. I have tried other viewers and got the same result.

I should point out that I am running Draw.io on Fedora Linux 38 and that I have installed Draw.io from Flathub.

**Comment by alderg** [comment] 2023-06-07 13:15
Can you attach the exported SVG for the above file? I'm getting a vector image for the icon in the diagram in the SVG export (using desktop draw.io on macOS).

**Comment by strate905** [comment] 2023-06-07 13:17
Please find attached the SVG file that my desktop app is generating.
![svg-export-test](https://github.com/jgraph/drawio/assets/58142069/8825914b-1e1c-4586-81ed-af8cd3ca925b)

**Comment by strate905** [comment] 2023-06-07 13:19
This is weird. It looks pixelated in the default viewer and in Inkscape, but it looks perfect in the above preview. 🤔

**Comment by alderg** [comment] 2023-06-07 14:34
Yes, the export looks OK. It might be the viewer. I'm closing this as it's not a bug in draw.io.

**Closed by alderg** 2023-06-07 14:34 UTC
