### ISSUE TITLE
Adding a extra blank page on exporting US-Tabloid(11''*17'') paper size

### ISSUE THREAD

**Issue by gautamyadav144** [jgraph/drawio#2328] opened 2021-10-18 07:36 UTC
**Describe the bug**
When i'm exporting pdf with page size US-Tabloid(11''*17'') landscape, its adding one blank page.

**To Reproduce**
1. Just a page with paper size  US-Tabloid(11''*17'') landscape.
2. Export as pdf.
3. See there will two pages with extra added blank page.

**Expected behavior**
There should be only one orginal page should not be blank page.

**Screenshots**
![image](https://user-images.githubusercontent.com/20815011/137687686-7fd73276-8611-48c9-862e-95e1f76f1822.png)

- draw.io version [15.4.1]

**Desktop ( following information):**
 - OS: Windows 10
 - Browser [chrome]
 - Version [94.0.4606.81]

**Comment by davidjgraph** [comment] 2021-12-23 09:41
Closing due to lack of reproduction case.

**Closed by davidjgraph** 2021-12-23 09:41 UTC
