### ISSUE TITLE
Allow page tabs to be resized to multiple rows

### ISSUE THREAD

**Issue by lparkernz** [jgraph/drawio#2041] opened 2021-05-20 21:11 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I have many page tabs I cannot read the labels

**Describe the solution you'd like**
Allow resizing of the tab area to permit multiple rows of page tabs and allow the labels to be read again

**Describe alternatives you've considered**
Splitting pages into separate diagrams, combining drawings on the same page

**Additional context**

**Comment by davidjgraph** [comment] 2021-05-20 21:53
Duplicate of #647

**Closed by davidjgraph** 2021-05-20 21:53 UTC
