### ISSUE TITLE
Not able to export

### ISSUE THREAD

**Issue by amitguptagwl** [jgraph/drawio#259] opened 2018-05-21 01:18 UTC
v8.6.5

When I'm trying to export it show me a new screen (previously it was different);

![screenshot from 2018-05-21 06-46-19](https://user-images.githubusercontent.com/7692328/40286215-ba5def30-5cc2-11e8-822e-cae3c7b468bb.png)

Whether I select on Device icon or download button, it opens a URL "https://exp.draw.io/ImageExport4/export" in browser and says "Bad Request". Everything was working fine few days back.

**Comment by alderg** [comment] 2018-05-21 06:40
This works for me. Are you using the offline or desktop app? What browser and operating system are you using and what are the steps to reproduce the problem?

**Comment by alderg** [comment] 2018-05-21 07:38
Thanks for the report, this will be fixed in the next release (as a workaround, select the group and all its descendants for selection only export in the current version).

**Closed by alderg** 2018-05-21 07:38 UTC
