### ISSUE TITLE
Export to PDF, not only Selected pages, but all

### ISSUE THREAD

**Issue by gil2013** [jgraph/drawio#3021] opened 2022-09-06 08:20 UTC
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I do File/Export as/PDF then I select only few pages (1 to 4 but not 5 to 11), the PDF contains all pages (1-11), not only the selected slice.

**To Reproduce**
1. Go to 'File'
2. Click on 'Export as'
3. Click on 'PDF'
4. On a file of more than 4 tabs, you can choose Pages, then select a range of pages "Pages 1 to 4"
5. Click "Export"

**Expected behavior**
When I do File/Export as/PDF then I select only few pages (1 to 4 but not 5 to 11), the PDF contains all pages (1-11), not only the selected slice.
In PDF created I expect to have pages/tabs 1 to 4, but I always have pages 1 to 11,

**Screenshots**
![image](https://user-images.githubusercontent.com/112934228/188582877-a587450c-d231-42b2-8db8-00855d284031.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- diagram.net for Windows version all versions up to 20.2.8 included

**Desktop (please complete the following information):**
 - OS: Windows 10 / 20H2

**Additional context**

**Comment by mararad** [comment] 2022-09-07 11:28
I couldn't reproduce at my place. Tested in Edge 105.0.1343.27 (Official build) (64-bit) and Chrome Version 105.0.5195.102 (Official Build) (64-bit) and only 1-4 pages were exported.

* Does it work for you in other browsers and Incognito mode with all browser extensions temporarily disabled?
* Also check if File > Print > Select pages > Print > Print to PDF/Save as PDF help?

**Comment by gil2013** [comment] 2022-09-07 11:45
This issue is in the Windows version, I didn't tested the online version.

**Comment by Ledbelly2142** [comment] 2022-10-06 18:12
I am experiencing the same/similar issue that may be related. Using Windows app version diagrams.net 20.3.0, Windows 10 environment. When exporting to PDF with page 2 set as a background, the PDF renders as 2 separate pages, no background on the page. However, when I export to png, the image renders correctly with a the background set.

**Comment by davidjgraph** [comment] 2022-11-19 21:34
Duplicate of https://github.com/jgraph/drawio-desktop/issues/707

**Closed by davidjgraph** 2022-11-19 21:34 UTC
