### ISSUE TITLE
Export as png with border : schema not full

### ISSUE THREAD

**Issue by yroseau** [jgraph/drawio#1888] opened 2021-03-19 08:34 UTC
When I export a schema as PNG with border, the schema don't full.

**To Reproduce**
1. Create a big schema
2. Export as PNG
3. Set border width to 50

**Expected behavior**
Display full schema 

**Screenshots**
![without border](https://user-images.githubusercontent.com/9842982/111752527-1db7f880-8896-11eb-9aeb-57f6982e73ae.jpg)
![with border 50px](https://user-images.githubusercontent.com/9842982/111752579-2ad4e780-8896-11eb-85b5-78da577de293.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.4.7

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 87

**Comment by mararad** [comment] 2021-03-22 13:45
Hi,

is it possible to send us the diagram file so we could test it (support@diagrams.net)?
No one is using Fedora, but will test with Win 10. 

Thanks,

**Comment by iulian3144** [comment] 2021-08-03 10:34
I'm reproducing this with version 14.6.13.
Looks like a duplicate of #1216.
It seems that it only reproduces with <100% zoom - smaller the zoom, bigger the bottom right crop. As an workaround, you can export after zooming to 100% (this works fine for me).
Also, if you zoom to more than 100% it crops from top left corner.

**Comment by davidjgraph** [comment] 2021-11-29 16:15
Duplicate of #1216

**Closed by davidjgraph** 2021-11-29 16:15 UTC
