### ISSUE TITLE
allow save to use uncompressed formatted xml

### ISSUE THREAD

**Issue by dmeatte** [jgraph/drawio#323] opened 2018-10-01 19:04 UTC
I'd like the option to have the save use uncompressed formatted xml like the text in the *Edit Diagram..* dialog. I'm saving these drawings in a git repo and it would be great for the text diffs to be meaningful.

**Comment by alderg** [comment] 2018-10-08 11:33
Duplicate of #231

**Closed by alderg** 2018-10-08 11:33 UTC

**Comment by vintprox** [comment] 2020-06-29 05:56
> Duplicate of #231

@alderg I beg to differ. This should be reopened as long as "Save" operation is **different** from "Export". Isn't there any option to always save uncompressed XML? It is more sufficient format for version control, because then you see changed graphs and coordinates without using application itself, including some changes invisible to the eye while working with drawio.

**Comment by alderg** [comment] 2020-06-30 04:27
Try File, Properties and uncheck "Compressed".

**Comment by vintprox** [comment] 2020-06-30 07:03
> Try File, Properties and uncheck "Compressed".

Ah, ok. Would be nice if there was also a global setting for it.

**Comment by alderg** [comment] 2020-06-30 07:43
See compressXml flag at https://desk.draw.io/support/solutions/articles/16000058316
