### ISSUE TITLE
Customisable Shortcuts

### ISSUE THREAD

**Issue by abhinandshibu** [jgraph/drawio#3631] opened 2023-05-29 13:29 UTC
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

For many who use drawio on a regular basis, it would be immensly useful to be able to configure your own shortcuts for many of the buttons to be able to do things quickly. So then the team wouldn't have to manually add shortcuts for different features and requests. 

For example, I like to left align the text in the rectangles, so every time I write text, I have to escape full screen, click on the left align button then enter back into full screen. So for me it would be useful to configure my own shortcut for that button.

Hence I believe customisable shortcuts for these different buttons can be very useful for people to speed up their workflow if they want to.

**Comment by davidjgraph** [comment] 2023-05-29 20:24
Duplicate of #1654

**Closed by davidjgraph** 2023-05-29 20:24 UTC
