### ISSUE TITLE
Can't load plugins in desktop

### ISSUE THREAD

**Issue by yonahforst** [jgraph/drawio#896] opened 2020-05-04 08:07 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can't load plugins using the desktop version.

**To Reproduce**
1. open desktop version
2. extras > plugins > add > https://jgraph.github.io/drawio/src/main/webapp/plugins/number.js
3. close app and reopen

**Expected behavior**
The numbers plugin should be loaded

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.0.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSx
 - Browser [e.g. chrome, safari] desktop
 - Version [e.g. 22] 13.0.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment] 2020-05-04 09:05
Duplicate of https://github.com/jgraph/drawio-desktop/issues/276

**Closed by davidjgraph** 2020-05-04 09:05 UTC

**Comment by yonahforst** [comment] 2020-05-04 12:28
oh man, i don't know how i didn't find that. sorry for the bother

**Comment by davidjgraph** [comment] 2020-05-04 12:39
It happens a lot because there are two projects, no biggie.
