### ISSUE TITLE
Connection lines do not change

### ISSUE THREAD

**Issue by cw-aiden-tk** [jgraph/drawio#3429] opened 2023-03-15 07:53 UTC
![스크린샷 2023-03-15 오후 4 48 57](https://user-images.githubusercontent.com/102131057/225242631-137934ea-b64d-4b4e-bffa-a7a100fb17b6.png)
- target service: app.diagrams.net (v21.0.6)
- issue: Connection lines do not change

**Comment by mararad** [comment] 2023-03-15 18:37
Reproduced in Chrome 111.0.5563.65 (Official Build) (64-bit) and FF 111.0 (64-bit)
"Waypoints" change in the Format panel showing a seleted one but this change is not reflected on "Waypoints" in the toolbar.

https://user-images.githubusercontent.com/44292306/225409363-59c2bb83-3e42-4307-94ae-e800562f014f.mp4

**Comment by cw-aiden-tk** [comment] 2023-03-16 04:46
The connection line selected from the toolbar was used as a global setting in previous versions.
Is there a way to use it as a global setting?

**Comment by alderg** [comment] 2023-03-16 05:11
Thanks for the report. This will be fixed in the next release. (If updateDefaultStyle is false, which is the [new default since v21.0.1](https://github.com/jgraph/drawio/discussions/3312), the global setting will be changed if the selection is empty.)

**Closed by alderg** 2023-03-16 05:11 UTC

**Comment by davidjgraph** [comment] 2023-03-17 18:18
Released in 21.0.7
