### ISSUE TITLE
[feature request] Remember export configs (checkboxes)

### ISSUE THREAD

**Issue by zhangciwu** [jgraph/drawio#967] opened 2020-06-09 12:30 UTC
![image](https://user-images.githubusercontent.com/3340597/84147189-8f555180-aa8f-11ea-88d9-b2aebca19cdb.png)

The `zoom` and `Border Width` are remembered after once usage, but below checkboxes are not, a little inconvenient that every time exporting need to alter the cheboxes

It would have better user experience if these could be remembered

**Comment by mararad** [comment] 2020-12-21 19:05
https://trello.com/c/PXRHSmpp/222-remember-export-to-choice

Not the same feature request but I thought it would be good to have it here cause it is related to remembering export of choice

**Comment by davidjgraph** [comment] 2023-10-02 16:37
Duplicate of #2729 (yes, it's newer, but has more votes).

**Closed by davidjgraph** 2023-10-02 16:37 UTC
