### ISSUE TITLE
shape gets added on the other side of the arrow by default

### ISSUE THREAD

**Issue by varadharajaan** [jgraph/drawio#3192] opened 2022-11-20 06:38 UTC
Preflight Checklist
 I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
[x]I have searched the issue tracker for a feature request that matches the one I want to file, without success.
Describe the bug
draw.io replicates the shape on the other side when drag an arrow line from it

To Reproduce

create rectangle shape
click on the shape and drag the arrow line out of it
when release the arrow pointed to one side, it replicates the shape what was created on the origin side
this is very annoying that i have delete the shape everytime to use only arrow.

attached an image in which only box and arrow to be expected but i am getting another box on the right side by default.

Expected behavior
no box or shape to be created on the other end by default

Screenshots
Screenshot 2022-11-20 at 11 58 33 AM

draw.io version (In the Help->About menu of the draw.io editor):

draw.io version - 20.5.3 browser
Desktop (please complete the following information):

Browser chrome
Smartphone (please complete the following information):

tested only in laptop
Additional context
please help to solve this issue

**Comment by varadharajaan** [comment] 2022-11-20 06:39
<img width="1679" alt="Screenshot 2022-11-20 at 11 58 33 AM" src="https://user-images.githubusercontent.com/13198892/202889400-851e9b7b-9571-4ac7-ab49-9a5a18a389b7.png">

**Comment by alderg** [comment] 2022-11-20 06:39
You created this ticket 3 times now. If you don't stop you will be banned.

**Comment by alderg** [comment] 2022-11-20 06:40
Duplicate of https://github.com/jgraph/drawio/issues/3190

**Closed by alderg** 2022-11-20 06:40 UTC
