### ISSUE TITLE
SVG Export - Preserve Layers

### ISSUE THREAD

**Issue by ThinkBriK** [jgraph/drawio#694] opened 2019-12-26 15:05 UTC
Hi all,

At the moment, SVG export is not translating Draw.io layers into SVG Layers (such as the ones used by Inkscape). It's a problem for me because I would use layers to make dynamic presentations using [Sozi](https://sozi.baierouge.fr/) and it's based on SVG layers.

You can create incredible presentations this way such as http://kube-decon.carson-anderson.com/Layers/0-Intro.sozi.html (video of the actual presentation : https://vimeo.com/245778144/4d1d597c5e)

**Comment by davidjgraph** [comment] 2021-01-23 08:22
Duplicate of #1775

**Closed by davidjgraph** 2021-01-23 08:22 UTC
Labels: wontfix
