### ISSUE TITLE
Gradient and/or blur the shadow of a shape

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1671] opened 2020-12-25 12:14 UTC
One feature i'd like to propose and think would highly improve many diagram looks into looking more professional out of the box is to gradient and/or blur the shadow of a shape. Right now it's a boolean attribute and one color. The added 3d effect and texture make things look more familiar esp. in diagrams w/ a lot of layers/boxes.

Proposed:
- feature one: blurred / not blurred shadow attribute.
- feature two: parametrize w/ x/y shadow offset, shadow color and blur intensity.
(I think some of those are already implemented in CSS/SVG).

https://desk.draw.io/a/tickets/10924

**Comment by ddidier** [comment] 2021-03-12 16:14
I was looking for this sorely missing feature, so I took a look around the code and [found this](https://github.com/jgraph/drawio/blob/533720a8c7fd283c68275d81f222e617a34428f6/src/main/webapp/js/diagramly/util/mxJsCanvas.js#L604). As far as I can tell `ctx` is a [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) so we should use [CanvasRenderingContext2D#shadowBlur](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/shadowBlur).

**Comment by ddidier** [comment] 2021-10-02 19:58
is there some news on this request?

**Comment by davidjgraph** [comment] 2021-10-02 20:42
The issue is declined through lack of interest from the core team.

**Comment by rusyn66** [comment] 2022-06-30 13:08
So is this implemented? This is the most important feature. I have to use cacoo.com just because they have shadow blurred compare to drawio which show just a second box and looks awful compare to cacoo box with shadow which looks natural.

**Comment by AymanProjects** [comment] 2022-09-14 04:27
We still want it 🤓

**Comment by henry-js** [comment] 2022-11-09 09:26
+1

**Comment by brsrom** [comment] 2022-11-23 06:51
+1000000000000000000000000

**Comment by AceDicer** [comment] 2022-11-27 15:54
+1

**Comment by karthifairhawn** [comment] 2022-12-21 07:07
+1

**Comment by MeGilles** [comment] 2023-01-27 14:33
+1

**Comment by bluetata** [comment] 2023-03-06 17:30
We still want it

**Comment by PaulGBarbu** [comment] 2023-05-27 10:41
Blurred shadows seem to already be a thing, but can only be applied globally (Have nothing selected > Diagram > Shadow). But unfortunately, it applies to everything. So the functionality seems to be there, am I maybe overlooking something?

**Comment by Ale-Naa** [comment] 2023-07-05 08:22
+1

**Comment by ivnilv** [comment] 2023-09-15 13:23
+1 

Why is this even marked as Closed ?

Come on now!

**Comment by josemoren** [comment] 2024-02-26 13:11
+1

**Comment by davidjgraph** [comment] 2024-02-28 15:44
I unsubscribed to this issue some time ago due to the amount of useless comments. So congrats, you pushed the issue back 6 months by spamming.

**Comment by davidjgraph** [comment] 2024-02-28 16:04
The bounding box calculation is hard per shape with the blurred shadows. It's a lot easier to apply globally and just add a bit to the overall bounds.

**Comment by davidjgraph** [comment] 2024-02-29 16:48
In 24.0.0.

**Closed by davidjgraph** 2024-02-29 16:48 UTC
Labels: feature request
