### ISSUE TITLE
C4 Model: Can not show container name

### ISSUE THREAD

**Issue by sang-hv** [jgraph/drawio#4312] opened 2024-04-04 10:27 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**
![Screenshot 2024-04-04 at 17 27 02](https://github.com/jgraph/drawio/assets/62000777/e46e85bd-615e-488b-9f87-17f84a2d3622)
![Screenshot 2024-04-04 at 17 27 13](https://github.com/jgraph/drawio/assets/62000777/11fb2000-ce99-48b3-92e7-12c5d1f2a3f9)

![Screenshot 2024-04-04 at 17 28 44](https://github.com/jgraph/drawio/assets/62000777/b7355ecb-40f7-4e86-9295-74c7a58c87bd)

![Screenshot 2024-04-04 at 17 28 56](https://github.com/jgraph/drawio/assets/62000777/1d254d2d-f9b7-465a-8af6-39528b80be1a)

- draw.io version v24.2.1

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by davidjgraph** [comment] 2024-04-04 10:36
The problem with C4 is we're getting one PR to fix some issue. That PR breaks something else, and round and round. Now we're at another apparent issue.

The C4 users in drawio need to work out exactly what the C4 shapes should show, collectively. We don't use C4, so have no idea what they are or what they should show.

**Comment by Rlexsu** [comment] 2024-04-09 03:25
I just encountered this issue while creating a diagram, removing the placeholder reveal the underlying issue
![image](https://github.com/jgraph/drawio/assets/13164382/7c891089-188a-40ac-b867-0f2b337092b3)
Note that for person the %c4Name% is at the top, but for Web Browser Container, Message Bus Container, Microservice Container, Data Container it is %c4Type% at the top instead of %c4Name%.
![image](https://github.com/jgraph/drawio/assets/13164382/0c58ce5b-32ff-41bd-9167-231c6c2ae86d)
So this effectively means that although we can key in c4Name as seen from picture above but it will not get displayed when it is being rendered.

**Comment by JasonBSteele** [comment] 2024-04-10 12:41
I agree with @Rlexsu, it is simply because the wrong template value (c4Type) has been used where c4Name should have been used. Can we please have a fix for this as it makes those shapes unusable?

If a PR were raised that addressed this issue, surely this wouldn't cause the breaking problems referred to by @davidjgraph ?

**Comment by davidjgraph** [comment] 2024-04-10 12:46
We'll accept a PR, yes.

**Comment by JasonBSteele** [comment] 2024-04-10 13:02
Ok, I have found where I think the fixes need to happen:
https://github.com/jgraph/drawio-app-engine/blob/f835e71d41970521143892d5bb5d8aaa9f60686f/src/main/webapp/js/diagramly/sidebar/Sidebar-C4.js#L136

We can see that several shapes in here don't have c4Name added to them and that seems to correlate with the shapes that have missing Names. Is there anyone here with experience with raising PRs for this project and better familiarity with the code that could fix this?

**Comment by Rlexsu** [comment] 2024-04-10 13:56
I can raise a PR but the readme on the main page stated that it is not open for contribution, so not sure what to do at this point

**Comment by davidjgraph** [comment] 2024-04-10 14:17
This is a mirror repo. Just raise it, I'll review and apply to the real repo.

**Comment by Rlexsu** [comment] 2024-04-10 14:41
@davidjgraph I've just checked and you already made the fix on v24.2.0 release with commit id 3dbd67a

**Comment by davidjgraph** [comment] 2024-04-10 15:08
That commit was taken from a PR on this repo. It broke other things.

**Comment by Rlexsu** [comment] 2024-04-10 15:21
@davidjgraph the dev(main) branch in this repo already contain the code change, so there's nothing I can do now

**Comment by davidjgraph** [comment] 2024-04-10 15:49
OK, but the problem is the changes weren't tested at all. They broke other things, this is why we don't accept PRs.

**Comment by paulwhippey** [comment] 2024-04-11 07:51
On the surface this should be a simple case of making these changes:

In file: https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/sidebar/Sidebar-C4.js

Change Line 95 to: 

`bg.setAttribute('label', '<font style="font-size: 16px"><b>%c4Name%</b></font><div>[%c4Type%:&nbsp;%c4Technology%]</div><br><div><font style="font-size: 11px"><font color="#E6E6E6">%c4Description%</font></div>');`
			    
Change Line 110 to:

`bg.setAttribute('label', '<font style="font-size: 16px"><b>%c4Name%</b></font><div>[%c4Type%:&nbsp;%c4Technology%]</div><br><div><font style="font-size: 11px"><font color="#E6E6E6">%c4Description%</font></div>');`
			
Change Line 125 to:

`bg.setAttribute('label', '<font style="font-size: 16px"><b>%c4Name%</b></font><div>[%c4Type%:&nbsp;%c4Technology%]</div><br><div><font style="font-size: 11px"><font color="#E6E6E6">%c4Description%</font></div>');`
			  
Change Line 140 to:

`bg.setAttribute('label', '<font style="font-size: 16px"><b>%c4Name%</b></font><div>[%c4Type%:&nbsp;%c4Technology%]</div><br><div><font style="font-size: 11px"><font color="#E6E6E6">%c4Description%</font></div>');`

I can raise a PR for just these changes if that is of help? Please don't remove the C4 shapes, I use them quite a lot in my work.

Many thanks.

**Comment by davidjgraph** [comment] 2024-04-11 18:13
Thanks for the suggestion, is the issue fixed at https://9930c8a5.drawio-dev.pages.dev/ ?

**Closed** 2024-04-19 05:53 UTC
Labels: help wanted
