### ISSUE TITLE
[IBM VPC] Container not always containing

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#724] opened 2020-01-22 15:48 UTC
In the attached example, the zone and subnet are containers, then the 2 VSIs icons were dragged into the subnet container.  
The expected outcome is that the 2 VSIs are now included with the subnet container and will move and duplicate whenever the subnet container is moved or duplicated.  
The actual outcome is that the 2 VSIs are not included with the container when the container is moved, the VSIs remain where they are.  This is currently reproducible in the attached example by dragging the VSIs out of the container and then dragging the VSIs back into the container.  As far as I can tell I'm doing this correctly but let me know if I'm missing something.

This scenario seems to happen a lot and eventually I can get the VSIs to be part of the container.  I wouldn't expect that I would need to manually group the VSIs and containers.

Thanks,
Jay

[ContainerNotContainingExample.drawio.zip](https://github.com/jgraph/drawio/files/4098154/ContainerNotContainingExample.drawio.zip)

**Comment by egrimate** [comment] 2020-01-30 12:20
Please let us know is this still an issue with the reworked shapes (boxes).

**Comment by jaywarfield** [comment] 2020-01-30 13:47
Will do, similar to what I mentioned in issue #723 this problem was also only happening with container=1 set, but with container=0 set and then grouping boxes in draw.io has a similar effect as containers where the group retains objects dragged into a box after the boxes have been grouped. 

As this time we will plan to stick to container=0 on draw.io.

Thanks!

**Comment by egrimate** [comment] 2020-01-30 15:18
I've set container=1 in group (box) shapes because they should behave like containers in my opinion. Test it and let me know. It can always be changed later.

**Comment by jaywarfield** [comment] 2020-01-30 15:54
Awesome, I agree with you that is a perfect use case for containers.  Previously I had container=1 for all boxes except I used container=0 for the dashed boxes named Security Group, Instance Group, and Resource Group.  The reason is that the 3 dashed boxes can be overlayed on multiple container boxes, so the user would create the diagram first using only container boxes, then drop the non-container dashed boxes where needed.  I did originally consider making the 3 dashed boxes as containers too but I concluded that the 3 dashed boxes should not be containers.  A container dashed box can probably still be overlayed on other boxes but it wouldn't make sense to put any objects directly inside the container dashed box because the dashed box needs to be flexible for resizing as needed, so that's when I concluded it would be best to make the 3 dashed boxes as non-containers.  I will try everything when published.  Thanks!

**Comment by jaywarfield** [comment] 2020-02-03 00:23
Changes published this weekend look awesome! I converted several secondary diagrams using Edit Style with cut-and-paste to get them quickly converted (realizing that the containers won't be set up properly since the objects were placed before some of the boxes were containers). The Subnet:ACL worked out well. This week I will convert the template published to draw.io from scratch so it will be created properly with all containers and will test out: 1. expansion problem (issue 723), 2. make sure objects stay in container (issue 724), and 3) revisit whether the 3 dashed groups should be a container. These changes are really excellent! Thanks!

**Comment by jaywarfield** [comment] 2020-02-04 00:22
Using the new boxes I was not able to reproduce this issue with icons not staying in a container box after an icon is dragged into the container box, so will close out and keep on eye on whether it happens.  Thanks!

**Comment by jaywarfield** [comment] 2020-02-04 01:35
I just ran across this issue with the new container boxes so reopening while I try to create a reproducible scenario.  When it happens it happens consistently, but then eventually the icon stays in the container.

**Comment by jaywarfield** [comment] 2020-02-05 00:36
Attached zip DragIconIntoContainerExmpleWithNewBoxes shows this issue with the new boxes.  
The scenario is:
1. There is an icon underneath all the boxes by itself.
2. Drag that icon and drop inside the nearest Subnet:ACL container directly above it.
3. Move that Subnet:ACL container around or move any of the surrounding containers to a different position.
4. The expected outcome is that the icon moves with the containers but the actual outcome is that the icons stays stationary and doesn't move indicating that the icon is not staying in the container.

[DragIconIntoContainerExampleWithNewBoxes.drawio.zip](https://github.com/jgraph/drawio/files/4156833/DragIconIntoContainerExampleWithNewBoxes.drawio.zip)

**Comment by jaywarfield** [comment] 2020-02-05 14:23
The scenario I just mentioned is consistently repeatable.  However, if I move the Subnet container outside all of the boxes, then drag the icon into the Subnet container, the icon remains in the container, then move the Subnet container back into place and the icon remains in the container.

Therefore, the problem appears to only happen with nested boxes where the icon doesn't stay in the Subnet container.

**Comment by jaywarfield** [comment] 2020-02-05 15:00
The scenario for icon text background color not changable from white to none didn't happen in a previous diagrams, but it is a problem with the attached zip when I add an icon to the canvas which has a different style.

Working Style:
aspect=fixed;perimeter=ellipsePerimeter;html=1;align=center;shadow=0;dashed=0;image;image=img/lib/ibm/vpc/PublicGateway.svg;fontColor=#000000;labelPosition=center;verticalLabelPosition=bottom;verticalAlign=top;fontSize=12;flipH=1;labelBackgroundColor=none;spacingTop=-5;

Nonworking Style:
aspect=fixed;perimeter=ellipsePerimeter;html=1;align=center;shadow=0;dashed=0;fontColor=#000000;labelBackgroundColor=none;fontSize=12;spacingTop=3;image;image=img/lib/ibm/vpc/PublicGateway.svg;flipH=1;

The nonworking style has the lableBackgroundColor=none but the format panel has checked the background color of white that can't be unchecked.  

The working style has additional settings and doesn't have a white label background.    

For now I can give users the working style that they can replace in the nonworking icon style.

I'm working on updating the ibm_vpc_architecture template to replace on draw.io but I want to make sure that there is no label background color and that icons stay in containers.

Thanks!

**Comment by jaywarfield** [comment] 2020-02-05 15:07
The previous diagram was probably created a year ago and when I added the shaded boxes they happened to work already with no label background color.  Therefore, could something have changed in the default icon styles (that I didn't change) since then that caused this problem on new diagrams now that I'm recreating the IBM template from scratch.  Seems to happen on all icons and I don't usual change the icon styles that I recall anyway.

**Comment by jaywarfield** [comment] 2020-02-06 14:57
Clarification: Adding one of our icons to a standalone Subnet container or standalone Zone container works consistently with the icon staying in the container, but any other box does not.  So to get the other boxes to retain icons I start out with a Subnet or Zone container, add icons, then change the style to another box such as the Region container, then nest boxes as the final step.

**Comment by egrimate** [comment] 2020-03-13 09:40
I couldn't reproduce this issue. The children of containers move correctly even by moving parents of containers. Please make sure you do not use any layers while testing this.

**Comment by egrimate** [comment] 2020-03-13 10:17
Testing showed that this happens in Firefox but not in Chrome, so if possible, please use Chrome in the meantime.

**Comment by egrimate** [comment] 2020-03-13 10:45
Will be fixed in next release.

**Closed by egrimate** 2020-03-13 10:45 UTC
Labels: stencils

**Comment by jaywarfield** [comment] 2020-03-13 12:17
I do use FF on Mac and Windows which it looks like I didn't mention in the description (will include browser next time), I haven't tried Safari or Chrome or IE to reproduce this problem, looking forward to the fix in next release, and will use Chrome in the meantime.  Thanks!
