### ISSUE TITLE
"Save As" clobbers current file

### ISSUE THREAD

**Issue by codebling** [jgraph/drawio#2446] opened 2021-11-26 00:05 UTC
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
A common workflow with most apps (e.g. Gimp, Inkscape) is to work on a file, save it, then edit a slight variation and save this under a new file name. Drawio saves the current file before creating the new file. 

**To Reproduce**
1. Create a new file. Add a rectangle with text "hello"
2. Save the file.
3. Add a second rectangle with text "second rectangle"
4. Save As a different file name
5. Open original file

**Expected behavior**
Original file contains rectangle with text "hello". 

**Actual behavior**
Original file contains 2 rectangles and both files are identical.

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 15.4.0 (desktop/electron build)

**Desktop (please complete the following information):**
 - OS: Arch 
 - package [drawio-desktop-15.4.0-1](https://aur.archlinux.org/packages/drawio-desktop/)
 - libnotify 0.7.9-2
 - electron 12.2.2

**Comment by davidjgraph** [comment] 2021-11-26 13:54
Duplicate of https://github.com/jgraph/drawio-desktop/issues/377

**Closed by davidjgraph** 2021-11-26 13:54 UTC

**Comment by codebling** [comment] 2021-11-26 17:06
Confirm that disabling autosave fixes the issue. (Didn't realise that was there!)
Thanks!!
