### ISSUE TITLE
Grouped objects dont move together

### ISSUE THREAD

**Issue by torian257x** [jgraph/drawio#3966] opened 2023-11-02 10:12 UTC
create a group

2 objects

try to move them together

doesnt work, moves single element of the group

tried in chrome and brave and firefox

it should move together like in this video

https://www.youtube.com/watch?v=1SIrmEthMNk

look at the video comments, 3 months and the bug is still there? I'm surprised.

**Comment by davidjgraph** [comment] 2023-11-02 12:43
Duplicate of #3967 . That's not actually our youtube channel, if people don't report it here, we don't know.

**Closed by davidjgraph** 2023-11-02 12:43 UTC
