### ISSUE TITLE
Text alignment can be changed in text editing mode, but jumps back 

### ISSUE THREAD

**Issue by jdittrich** [jgraph/drawio#46] opened 2017-01-08 13:51 UTC
**Reproduction:**
1. Draw a (rectangle) shape
2. write some text in it. It is usually center-aligned (adhering to whatever you specified before)
3. Double click the text/mark it and change its alignment (e.g. to left-aligned): ![bildschirmfoto vom 2017-01-08 14-48-17](https://cloud.githubusercontent.com/assets/3416487/21750357/8c8c563a-d5b1-11e6-9051-14ae37193cc6.png)
4. Click something else: 
![bildschirmfoto vom 2017-01-08 14-48-26](https://cloud.githubusercontent.com/assets/3416487/21750358/99f7a64e-d5b1-11e6-92b9-1969eccbe87a.png)

**What happens:** The text jumps back from the right-aligned to center-aligned again
**What should happen:** The text should stay right aligned

**Comment by alderg** [comment] 2017-01-10 09:06
Select the cell, not the text, then click on the alignment button.

**Comment by davidjgraph** [comment] 2017-01-10 09:06
Yeah, we're not able to format whilst editing, currently.

**Comment by jdittrich** [comment] 2017-01-10 14:54
@davidjgraph not formatting while editing would be also totally fine. The problem is that I can halfway do it nevertheless: The alignment buttons can be clicked, the alignment changes etc. 

This would change my *"what should happen"* alternatively to something like: *"Changing a text alignment in edit mode should not be possible. Formatting options which can't be applied (like alignment) should not cause changes, or better, be deactivated in the first place"*

**Comment by viion** [comment] 2018-02-01 13:01
Hello,

I am confused about this ....

> Select the cell, not the text, then click on the alignment button.

There is no alignment button as far as I can see when you select the cell

> Yeah, we're not able to format whilst editing, currently.

Does this mean regardless of your text alignment, it isn't visually shown? When is it shown? It doesn't work if you export it, it goes back to the center.

Is the alignment just a dead option that doesn't work?

**Comment by alderg** [comment] 2018-02-08 10:34
The alignmnt when text is selected is relative to the text block (ie it's ignored for a single line).
The alignment button for selected cells is in the text tab of the format panel.

**Comment by Ma-XX-oN** [comment] 2018-10-16 19:51
> The alignmnt when text is selected is relative to the text block (ie it's ignored for a single line).

Ugh!  Why is it ignored for a single line?  Alignment should be available for 1 or more lines relative to the text bounding box, not just centre a text box inside of the bounding box and only allow changing the alignment inside of the text box.  That is very bizarre and unexpected behaviour.

What other text formatting application does this ever occur?  Why would you ever do this?  Why? _Why?_ **_WHY?_** 😱

Please correct this.

**Comment by davidjgraph** [comment] 2018-10-16 19:53
You are welcome to submit a PR for it.

**Comment by Ma-XX-oN** [comment] 2018-10-16 20:04
Ok @davidjgraph, what would the steps be to do that?  I know JS, but I don't know how I would pull it down to my machine, modify it and test it there.

**Comment by Ma-XX-oN** [comment] 2018-10-16 20:36
Oh, I see why this is done this way.

![image](https://user-images.githubusercontent.com/10625935/47045739-8ba9e400-d161-11e8-847b-17e24d24857a.png)

The **Position** states where the text is located relative to the bounding box.  The image here shows it as **left**, so it is left of the bounding box.  **Center**, means centre relative to the bounding box.  In all cases though, the width of the bounding box is respected, regardless of where it is located relative to the bounding box.

I've never seen anything like this before.  This would require a flag use the bounding box instead of the **Position** so as not to break older files.

**Comment by chriswolf-nrg** [comment] 2019-01-24 23:02
Why is this closed?  In Microsoft Visio, I can set the text alignment to be top and left-justified but not with draw.io - a major show-stopper when using nested shapes.

**Comment by alderg** [comment] 2020-02-12 16:28
This issue should be fixed.

**Closed by alderg** 2020-02-12 16:28 UTC

**Comment by MrRobboto** [comment] 2021-07-02 15:09
Funny I'm just running into this now. Maybe they fixed something but from the above screenshot it looks like you could always do this in the text formatting tab with the shape selected. It's not position, it's the button above that...

![image](https://user-images.githubusercontent.com/14045888/124294615-e3612700-db25-11eb-9eb5-d065505ef003.png)
