### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1572] opened 2020-12-08 14:08 UTC
I would like to request Git Hub Enterprise integration
I have implemented it for our environment (based off the Git Hub integration) but would be good to get this pushed upstream.
Given that this needs an app integration on the private GHE server, and tomcat to run the authorization flow, I expect that this would be an option to build a site local draw.io with local GHE support - rather than something that would show on https://draw.io/

**Comment by Fullchee** [comment] 2021-01-04 19:59
Is this a duplicate of #473?

**Comment by davidjgraph** [comment] 2021-01-04 20:31
Duplicate #473

**Comment by GitHubFor122** [comment] 2021-04-16 13:14
this feature was already enabled ?

**Comment by davidjgraph** [comment] 2021-04-16 13:15
No, there are no plans to implement this.

**Comment by GitHubFor122** [comment] 2021-04-16 13:18
what is target implemention plan? that is pretty nice feature

**Comment by davidjgraph** [comment] 2021-04-16 13:19
There are no plans to implement this.

**Comment by GitHubFor122** [comment] 2021-04-16 13:20
what is reason?resource limiation?

**Comment by davidjgraph** [comment] 2021-04-16 13:22
I have no interest in writing the integration.

**Comment by GitHubFor122** [comment] 2021-04-16 13:31
can i contrbute it ?

**Comment by davidjgraph** [comment] 2021-04-16 13:32
Yes, if it's professional writen and fully tested. If it's crap we'll throw it away.

**Comment by GitHubFor122** [comment] 2021-04-28 13:47
Would you share me some logic how to implement Github?

**Comment by davidjgraph** [comment] 2021-04-28 13:49
I have no idea what the Github Enterprise API looks like, I've never used it.

**Comment by GitHubFor122** [comment] 2021-04-28 13:54
like http(s)://[hostname]/api/v3,   I suppose if github url can be parametered, then it is easy to intergreate enterprise github

**Comment by GitHubFor122** [comment] 2021-04-28 14:43
If github url can be parametered,  then i can test in our internal enterpirse github

**Comment by davidjgraph** [comment] 2021-04-28 14:55
https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/GitHubClient.js

**Comment by GitHubFor122** [comment] 2021-04-28 15:42
seems need to install a Oauth application? where is callback url?

**Comment by GitHubFor122** [comment] 2021-04-28 17:13
https://github.com/jgraph/drawio/blob/master/src/main/java/com/mxgraph/online/GitHubServlet.java this file hardcode github url too

**Comment by GitHubFor122** [comment] 2021-04-29 05:03
It works on enterpise github, what did I do
1. create a Github OAuth app
2. replace all hardcode client id  to OAuth APP client id
3. config /WEB-INF/github_client_secret
4. replace api.github.com to [hostname]/api/v3
5. replace https://github.com to htttps://<hostname>
6. added below code
https://github.com/jgraph/drawio/blob/master/src/main/java/com/mxgraph/online/GitHubServlet.java

> 			String url = "https://github.com/login/oauth/access_token";
> 			String githubURL = System.getenv("GITHUB_URL");
> 			if(githubURL != null||githubURL!=""){
> 				url = githubURL+"/login/oauth/access_token";
> 				System.out.println(url)
> 
> 			}

Suggestion:
parameter github config

**Comment by davidjgraph** [comment] 2021-04-29 11:13
Thanks for looking into it. We made some similar changes in 14.6.8. See if you can get that release working without any code changes.

**Comment by GitHubFor122** [comment] 2021-04-29 12:44
Not working ,  Github Authorize poppup will redirect to github.com,

**Comment by GitHubFor122** [comment] 2021-04-29 12:47
seems need to change DRAWIO_GITHUB_API_URL and DRAWIO_GITHUB_RUL in js/diagramly/init.js.  let me try it

**Comment by davidjgraph** [comment] 2021-04-29 12:48
Yes , change all three of the github values in init.js and pull the recent commit

**Comment by GitHubFor122** [comment] 2021-04-29 13:02
Github Authorize poppup page still redirect to github.com,  seems init.js deosn't take effective

**Comment by davidjgraph** [comment] 2021-04-29 13:09
how are you running the build, using a servlet engine like tomcat? You need to set https://github.com/jgraph/drawio/blob/master/src/main/webapp/WEB-INF/github_auth_url also.

**Comment by GitHubFor122** [comment] 2021-04-29 13:17
yes ,war package inside tomcat,  Authorization required popup page redirect to github.com
What I changed
1. WEB-INF/github_auth_url
2. WEB-INF/github_client_id
3. WEB-INF/github_client_secret
4. DRAWIO_GITHUB_API_URL and DRAWIO_GITHUB_RUL, js/diagrmly/Init.js

**Comment by davidjgraph** [comment] 2021-04-29 13:22
Set the JS variables in PreConfig, https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/PreConfig.js

**Comment by GitHubFor122** [comment] 2021-04-29 13:35
/github2?getState=1 doesn't get github acccess_token, reposnse body like: s167ehe6sfasdd909fdsadlfl

**Comment by davidjgraph** [comment] 2021-04-29 13:36
what's the response from that github2 call in the debugger?

**Comment by GitHubFor122** [comment] 2021-04-29 14:28
seems Github in  https://app.diagrams.net/ has same issue

**Comment by davidjgraph** [comment] 2021-04-29 15:20
That issue online is fixed in 14.6.9, it's a different problem, the app ID sent was wrong.

**Comment by GitHubFor122** [comment] 2021-04-29 15:39
what is Github OAuth app homepage URL, and callback url standard ?

**Comment by davidjgraph** [comment] 2021-04-29 15:56
The callback for the online app is https://app.diagrams.net/github2. Not sure what you mean by Github OAuth app homepage URL

**Comment by GitHubFor122** [comment] 2021-04-29 16:12
failed again , /github2?getState=1 is unable to get github access token

**Comment by davidjgraph** [comment] 2021-04-29 16:19
I'd need detailed about the outgoing request. If the app ID being sent your app ID?

**Comment by GitHubFor122** [comment] 2021-04-29 16:26
What i did:
1. Create a Enterpise github Oauth APP,  callback is http://[host]:8080/github.html
2. Change WEB-INF/github_auth_url
3. Change  WEB-INF/github_client_id from Enperprise Github OAuth APP
4. Change WEB-INF/github_client_secret  from Enperprise Github OAuth APP
 5. Configure DRAWIO_GITHUB_API_URL,DRAWIO_GITHUB_ID(same as WEB-INF/github_client_id) and DRAWIO_GITHUB_RUL, js/PreConfig.js

**Comment by davidjgraph** [comment] 2021-04-29 16:28
1. Can the server running the war correctly resolve the host?
2. In 4 I assume your mean the secret, not the app ID
3. can you show me the preconfig?

I need the details of the outgoing call for the auth and the reponse details.

**Comment by GitHubFor122** [comment] 2021-04-29 16:33
1.  yes, can 
2. yes , it is clilent secret
3.
window.DRAWIO_GITHUB_URL = "https://alm-github.com"
window.DRAWIO_GITHUB_URL = "https://alm-github.com/api/v3"
window.DRAWIO_GITHUB_ID = 'f789aa4919c5b0a71a4'

**Comment by davidjgraph** [comment] 2021-04-29 16:36
Second is window.DRAWIO_GITHUB_API_URL, "API" missing

**Comment by GitHubFor122** [comment] 2021-04-29 16:39
it is DRAWIO_GITHUB_API_URL ,  my type issue.  our network retricts internet. i type with my personal laptop

**Comment by GitHubFor122** [comment] 2021-04-29 16:48
haven't got any clue

**Comment by GitHubFor122** [comment] 2021-04-29 16:51
failed github endpoint:  /api/v3/user with 401 code,  I guess don't get github access token from previous steps, but no idea which step to retrive github access token?  via /github2?

**Comment by davidjgraph** [comment] 2021-04-29 16:52
We'll get a GitHub Enterprise license and test it ourselves to check it works.

**Comment by GitHubFor122** [comment] 2021-04-29 16:56
Root cause is obovious,  but i am not fimilar to code logic.
it is working last night with old version,  previous version,  drawio endpoint /github will return a github access token, next call, will utilize the token
but new version 14.6.9,  which code to retrive github access token,  via /github2?

**Comment by davidjgraph** [comment] 2021-04-29 16:58
The old code performed an implicit grant (i.e. client-side auth). That is less secure, so we switched to server-flow.

There is a new servlet in the java code, GitHubAuthServlet, that is the servlet now used. The JS is still the same file.

**Comment by GitHubFor122** [comment] 2021-04-29 17:02
so Finnally GitHubAuthServlet repsonses what ?  seems it is not access token

**Comment by GitHubFor122** [comment] 2021-04-30 04:58
after restarted tomcat, it is working now on 14.6.9

**Comment by davidjgraph** [comment] 2021-04-30 06:10
So it's working just setting those 6 values in 14.6.9?

**Comment by GitHubFor122** [comment] 2021-04-30 06:14
Yes,
1. PreConfig.js
window.DRAWIO_GITHUB_URL
window.DRAWIO_GITHUB_API_URL
window.DRAWIO_GITHUB_ID
2. WEB-INF/github_auth_url, github_client_id, github_client_secret

**Comment by davidjgraph** [comment] 2021-04-30 06:15
Cool, I'll closed the issue then.

**Closed by davidjgraph** 2021-04-30 06:15 UTC
Labels: feature request

**Comment by GitHubFor122** [comment] 2021-04-30 06:17
One more attention,  Github Oauth callback url ?  can we aligin it.   I am afraid new coming version , will change it .

**Comment by davidjgraph** [comment] 2021-04-30 06:20
It's something we can set in a variable since a servlet is required. We had to create a new servlet for the new authentication flow since it's a large change in the way authenication is performed. But, we left the old servlet, /github, in place for compatibility, you can assume we'd do the same thing for this one.

**Comment by GitHubFor122** [comment] 2021-04-30 07:31
What is NOTIFICATION_URL? I would like to utilize it ? Can brief to me ?

**Comment by davidjgraph** [comment] 2021-04-30 08:01
That off-topic, please start a [discussion](https://github.com/jgraph/drawio/discussions) for subjects not relating to the topic of this issue.

**Comment by nkagarw** [comment] 2021-07-24 09:05
What is DRAWIO_GITHUB_ID here ? The default value for that in the code is '4f88e2ec436d76c2ee6e'. Is it some kind of code associated with the GitHub enterprise user id of the user ? How can I retrieve it ?
